import type {PublicTheme} from './theme-contracts';
import type {Locale} from './locales';
import type {PublicServiceTranslation} from './service-translation-contracts';
export type Service = { categoryPath?:string[]; sourceLanguage?:Locale; translations?:Partial<Record<Locale,PublicServiceTranslation>>; id: string; name: string; description: string; category: string; priceFrom: number; durationFrom: number; priceTo?:number; durationTo?:number };
export type Staff = { serviceDetails?:Array<{serviceId:string;price:number;duration:number}>; publicPhone?:string; id: string; name: string; title: string; bio?: string; photoUrl?: string; serviceIds: string[] };
export type Catalog = { theme?:PublicTheme; tenant: { contactPhone?:string;contactEmail?:string;reminderMinutes?:number|null; bookingTerms?:string; defaultLanguage?:'et'|'en'|'ru';name: string; slug: string; address: string; timezone: string; description: string; cancellationHours: number; rulesVersion:number; demo: boolean }; services: Service[]; staff: Staff[]; today: string; maxDate: string; selectedStaffId?: string };
export type NextAvailability = { date: string | null; searchedThrough: string; hasMore: boolean };
export type Offer = { staffId: string; staffName: string; serviceId: string; start: string; end: string; price: number; duration: number };
export type BookingInput = { smsReminder?:boolean; emailReminder?:boolean; language?:'et'|'en'|'ru'; serviceId: string; staffId: string; start: string; expectedPrice: number; expectedDuration: number; expectedRulesVersion:number; name: string; email: string; phone?: string };
export type BookingResult = { language?:'et'|'en'|'ru'; id: string; reference: string; serviceName: string; staffName: string; start: string; end: string; price: number; duration: number; cancellationHours?:number|null; status: string;version?:number;managementUrl?:string;managementExpiresAt?:string;currentVersion?:number;currentStatus?:string };
