import {beforeAll,afterAll,beforeEach,afterEach,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import pg from 'pg';
import {mergeCustomers} from '../src/lib/customer-merge';
import {customerState,correctCustomer} from '../src/lib/customer-management';
import {exportCustomerData,previewContactRemoval,removeCustomerContacts} from '../src/lib/customer-privacy';
import {withTenant} from '../src/lib/db';
import {retentionState,changeRetention} from '../src/lib/retention';
import type {Actor} from '../src/lib/access';
const db=new pg.Client({connectionString:process.env.MIGRATION_DATABASE_URL});
let tenantId:string,owner:Actor,staffId:string,serviceId:string,sequence:number;
beforeAll(()=>db.connect());afterAll(()=>db.end());
beforeEach(async()=>{
 tenantId=randomUUID();staffId=randomUUID();serviceId=randomUUID();sequence=0;owner={id:randomUUID(),name:'Owner',email:randomUUID()+'@example.invalid',emailVerified:true,twoFactorEnabled:true,isPlatformAdmin:false};
 await db.query("INSERT INTO tenants(id,slug,name,address) VALUES($1,$2,'Merge company','Test')",[tenantId,'merge-'+tenantId]);
 await db.query('INSERT INTO auth_user(id,name,email,email_verified,two_factor_enabled) VALUES($1,$2,$3,true,true)',[owner.id,owner.name,owner.email]);
 await db.query("INSERT INTO memberships(tenant_id,user_id,role) VALUES($1,$2,'owner')",[tenantId,owner.id]);
 await db.query("INSERT INTO staff(id,tenant_id,name) VALUES($1,$2,'Staff')",[staffId,tenantId]);
 await db.query("INSERT INTO services(id,tenant_id,name,category) VALUES($1,$2,'Service','Test')",[serviceId,tenantId]);
});
afterEach(async()=>{
 for(const table of ['contact_removals','retention_policies','customer_merges','booking_events','booking_management_tokens','booking_requests','outbox','export_jobs','bookings','memberships','access_audit_log','staff','services'])await db.query('DELETE FROM '+table+' WHERE tenant_id=$1',[tenantId]);
 await db.query('DELETE FROM tenants WHERE id=$1',[tenantId]);await db.query('DELETE FROM auth_user WHERE id=$1',[owner.id]);
});
async function booking(name:string){
 const start=new Date(Date.now()+(++sequence)*86400000),end=new Date(start.getTime()+1800000);
 return (await db.query("INSERT INTO bookings(tenant_id,reference,staff_id,service_id,staff_name,service_name,customer_name,customer_email,start_at,end_at,occupied,price,duration,buffer_before,buffer_after) VALUES($1,$2,$3,$4,'Staff','Service',$5,'shared@example.invalid',$6,$7,tstzrange($6,$7,'[)'),1000,30,0,0) RETURNING *",[tenantId,randomUUID(),staffId,serviceId,name,start,end])).rows[0];
}
const command=(sourceId:string,targetId:string)=>({tenantId,requestKey:randomUUID(),sourceId,targetId,sourceVersion:1,targetVersion:1,reason:'Confirmed duplicate of the same individual',confirmed:true});
it('removes selected contacts and aliases, revokes links and exports, and prevents restoration',async()=>{
 const first=await booking('Person to remove'),alias=await booking('Old name to remove'),other=await booking('Different person');
 await mergeCustomers(owner,command(alias.customer_id,first.customer_id));
 await correctCustomer(owner,{tenantId,customerId:first.customer_id,version:2,name:'Corrected person',email:'corrected@example.invalid',phone:'',reason:'Private old name to remove'});
 let preview=await previewContactRemoval(owner,tenantId,first.customer_id);
 expect(preview).toMatchObject({bookings:2,futureBookings:2,canRemove:false});
 const request=()=>({tenantId,customerId:first.customer_id,fingerprint:preview.fingerprint,confirmed:true,identityConfirmed:true});
 await expect(removeCustomerContacts(owner,request())).rejects.toMatchObject({code:'FUTURE_BOOKINGS'});
 await db.query("UPDATE bookings SET status='cancelled',version=version+1 WHERE tenant_id=$1 AND id=ANY($2::uuid[])",[tenantId,[first.id,alias.id]]);
 await expect(removeCustomerContacts(owner,request())).rejects.toMatchObject({code:'VERSION_CONFLICT'});
 await db.query("INSERT INTO booking_management_tokens(tenant_id,booking_id,token_hash,expires_at,after_end_hours,encrypted_token) VALUES($1,$2,$3,clock_timestamp()+interval '1 day',24,'old-encrypted-token')",[tenantId,first.id,'a'.repeat(64)]);
 await db.query("INSERT INTO booking_events(tenant_id,booking_id,action,reason,before_data,after_data) VALUES($1,$2,'booking.cancel','Private person reason','{\"attentionReason\":\"private\"}','{\"attentionReason\":\"private\",\"status\":\"cancelled\"}')",[tenantId,first.id]);
 await db.query("INSERT INTO export_jobs(tenant_id,request_key,requested_by,scope,expires_at) VALUES($1,$2,$3,'{}',clock_timestamp()+interval '1 day')",[tenantId,randomUUID(),owner.id]);
 preview=await previewContactRemoval(owner,tenantId,first.customer_id);expect(preview).toMatchObject({canRemove:true,exports:1});
 expect(await removeCustomerContacts(owner,request())).toMatchObject({removed:true,alreadyRemoved:false,filesPending:false});
 expect(await removeCustomerContacts(owner,request())).toMatchObject({alreadyRemoved:true});
 const cards=(await db.query('SELECT * FROM customers WHERE tenant_id=$1 AND id=ANY($2::uuid[])',[tenantId,[first.customer_id,alias.customer_id]])).rows;
 expect(cards.every(c=>c.name==='[removed]'&&c.email===null&&c.source_key.startsWith('redacted:')&&c.contact_redacted_at)).toBe(true);
 const rows=(await db.query('SELECT customer_name,customer_email,customer_phone,contact_redacted_at FROM bookings WHERE tenant_id=$1 AND id=ANY($2::uuid[])',[tenantId,[first.id,alias.id]])).rows;
 expect(rows.every(b=>b.customer_name==='[removed]'&&b.customer_email===null&&b.customer_phone===null&&b.contact_redacted_at)).toBe(true);
 expect((await db.query('SELECT customer_name FROM bookings WHERE id=$1',[other.id])).rows[0].customer_name).toBe('Different person');
 const audits=(await db.query('SELECT metadata FROM access_audit_log WHERE tenant_id=$1',[tenantId])).rows;
 expect(JSON.stringify(audits)).not.toMatch(/Corrected person|corrected@example|Old name|Private old/);
 expect((await db.query('SELECT reason,after_data FROM booking_events WHERE tenant_id=$1',[tenantId])).rows[0]).toEqual({reason:'',after_data:{status:'cancelled'}});
 expect((await db.query('SELECT revoked_at,encrypted_token FROM booking_management_tokens WHERE tenant_id=$1',[tenantId])).rows[0]).toMatchObject({encrypted_token:null,revoked_at:expect.any(Date)});
 expect((await db.query('SELECT status,claim_token FROM export_jobs WHERE tenant_id=$1',[tenantId])).rows[0]).toEqual({status:'cancelled',claim_token:null});
 expect((await db.query('SELECT customer_ids,booking_ids FROM contact_removals WHERE tenant_id=$1',[tenantId])).rows).toHaveLength(1);
 await expect(correctCustomer(owner,{tenantId,customerId:first.customer_id,version:4,name:'Restore person',email:'restored@example.invalid',phone:'',reason:'Restore old contact'})).rejects.toMatchObject({code:'CONTACTS_REMOVED'});
 await expect(db.query("UPDATE customers SET name='Restore' WHERE id=$1",[first.customer_id])).rejects.toMatchObject({code:'23514'});
 await expect(db.query("UPDATE bookings SET customer_email='restore@example.invalid' WHERE id=$1",[first.id])).rejects.toMatchObject({code:'23514'});
 expect((await booking('Person to remove')).customer_id).not.toBe(first.customer_id);
});
it('enforces legal holds and owner checks inside both service and database removal',async()=>{
 const first=await booking('Held person');
 await db.query("UPDATE bookings SET status='cancelled',version=version+1 WHERE id=$1",[first.id]);
 await changeRetention(owner,{tenantId,version:0,retainDays:null,legalHold:true,confirmed:true});
 const preview=await previewContactRemoval(owner,tenantId,first.customer_id);
 expect(preview.legalHold).toBe(true);
 await expect(removeCustomerContacts(owner,{tenantId,customerId:first.customer_id,fingerprint:preview.fingerprint,identityConfirmed:true,confirmed:true})).rejects.toMatchObject({code:'LEGAL_HOLD'});
 await expect(withTenant(tenantId,async c=>{await c.query("SELECT set_config('app.user_id',$1,true)",[owner.id]);await c.query('SELECT remove_customer_contacts($1,$2)',[tenantId,first.customer_id]);})).rejects.toMatchObject({code:'23514'});
 await expect(withTenant(tenantId,c=>c.query('SELECT remove_customer_contacts($1,$2)',[tenantId,first.customer_id]))).rejects.toMatchObject({code:'42501'});
});
it('keeps retention inactive by default and versions owner-approved changes and legal holds',async()=>{
 expect(await retentionState(owner,tenantId)).toMatchObject({version:0,retainDays:null,automationEnabled:false,legalHold:false});
 const d={tenantId,version:0,retainDays:730,legalHold:true,confirmed:true};
 await expect(changeRetention(owner,{...d,confirmed:false})).rejects.toMatchObject({code:'INVALID_INPUT'});
 const results=await Promise.allSettled([changeRetention(owner,d),changeRetention(owner,d)]);
 expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);
 expect(results.find(r=>r.status==='rejected')).toMatchObject({reason:{code:'VERSION_CONFLICT'}});
 expect(await retentionState(owner,tenantId)).toMatchObject({version:1,retainDays:730,legalHold:true,automationEnabled:false});
 expect(await changeRetention(owner,{...d,version:1,retainDays:null})).toMatchObject({version:2,retainDays:null,approvedAt:null,legalHold:true});
 await db.query("UPDATE memberships SET role='receptionist' WHERE tenant_id=$1",[tenantId]);
 await expect(changeRetention(owner,{...d,version:2})).rejects.toMatchObject({code:'FORBIDDEN'});
 await expect(retentionState(owner,tenantId)).rejects.toMatchObject({code:'FORBIDDEN'});
});
it('exports only the selected person and explicit aliases, with owner and identity checks',async()=>{
 const first=await booking('First person'),alias=await booking('Same person old name'),other=await booking('Other person shared email');
 const request={tenantId,customerId:first.customer_id,identityConfirmed:true};
 await expect(exportCustomerData(owner,{...request,identityConfirmed:false})).rejects.toMatchObject({code:'INVALID_INPUT'});
 await expect(exportCustomerData(owner,{...request,customerId:randomUUID()})).rejects.toMatchObject({code:'CUSTOMER_NOT_FOUND'});
 const initial=await exportCustomerData(owner,request);
 expect(initial.profiles.map(r=>r.id)).toEqual([first.customer_id]);
 expect(initial.bookings.map(r=>r.id)).toEqual([first.id]);
 expect(JSON.stringify(initial)).not.toContain(other.customer_name);
 expect(initial.profiles[0]).not.toHaveProperty('source_key');
 await mergeCustomers(owner,command(alias.customer_id,first.customer_id));
 const merged=await exportCustomerData(owner,{...request,customerId:alias.customer_id});
 expect(merged.customerId).toBe(first.customer_id);expect(merged.profiles).toHaveLength(2);expect(merged.bookings).toHaveLength(2);
 expect(JSON.stringify(merged)).not.toContain(other.customer_name);
 const log=(await db.query("SELECT metadata FROM access_audit_log WHERE tenant_id=$1 AND action='customer.privacy_export'",[tenantId])).rows;
 expect(log).toHaveLength(2);expect(JSON.stringify(log)).not.toContain('shared@example.invalid');
 await db.query("UPDATE memberships SET role='receptionist' WHERE tenant_id=$1",[tenantId]);
 await expect(exportCustomerData(owner,request)).rejects.toMatchObject({code:'FORBIDDEN'});
});
it('merges only selected cards, preserves snapshots and routes future exact contact matches through aliases',async()=>{
 const first=await booking('First name'),second=await booking('Second name');
 const d=command(first.customer_id,second.customer_id);
 const results=await Promise.all([mergeCustomers(owner,d),mergeCustomers(owner,d)]);expect(results[0]).toEqual(results[1]);expect(results[0].bookingsMoved).toBe(1);
 const after=(await db.query('SELECT * FROM bookings WHERE id=$1',[first.id])).rows[0];
 expect(after.customer_id).toBe(second.customer_id);expect(after.customer_name).toBe(first.customer_name);expect(after.version).toBe(first.version);expect(after.start_at).toEqual(first.start_at);
 expect((await booking('First name')).customer_id).toBe(second.customer_id);
 const state=await customerState(owner,{tenantId,customerId:second.customer_id});
 if('csv' in state)throw Error('Expected JSON');expect(state.history).toHaveLength(3);expect(state.merges[0].metadata.source.id).toBe(first.customer_id);
  const all=await customerState(owner,{tenantId});if('csv' in all)throw Error('Expected JSON');expect(all.customers).toHaveLength(1);
 const byOldName=await customerState(owner,{tenantId,search:'First name'});if('csv' in byOldName)throw Error('Expected JSON');expect(byOldName.customers[0].id).toBe(second.customer_id);
 const third=await booking('Third name');
 await mergeCustomers(owner,{...command(second.customer_id,third.customer_id),sourceVersion:2});
 expect((await booking('First name')).customer_id).toBe(third.customer_id);
 expect((await db.query('SELECT merged_into_id FROM customers WHERE id=$1',[first.customer_id])).rows[0].merged_into_id).toBe(third.customer_id);
});
it('rejects stale, foreign, unauthorized and changed retry requests',async()=>{
 const first=await booking('First name'),second=await booking('Second name'),d=command(first.customer_id,second.customer_id);
 await expect(mergeCustomers(owner,{...d,targetId:randomUUID()})).rejects.toMatchObject({code:'CUSTOMER_NOT_FOUND'});
 await expect(mergeCustomers(owner,{...d,sourceVersion:2})).rejects.toMatchObject({code:'VERSION_CONFLICT'});
 await db.query("UPDATE memberships SET role='staff',staff_id=$2 WHERE tenant_id=$1",[tenantId,staffId]);
 await expect(mergeCustomers(owner,d)).rejects.toMatchObject({code:'FORBIDDEN'});
 await db.query("UPDATE memberships SET role='owner',staff_id=NULL WHERE tenant_id=$1",[tenantId]);
 await mergeCustomers(owner,d);
 await expect(mergeCustomers(owner,{...d,reason:'Different reason in a repeated request'})).rejects.toMatchObject({code:'IDEMPOTENCY_MISMATCH'});
 await expect(correctCustomer(owner,{tenantId,customerId:first.customer_id,version:2,name:'Changed name',email:'',phone:'',reason:'Alias correction'})).rejects.toMatchObject({code:'VERSION_CONFLICT'});
});
