import {beforeAll,afterAll,beforeEach,afterEach,it,expect,vi} from 'vitest';
import {randomUUID} from 'node:crypto';
import {mkdtemp,readdir,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import pg from 'pg';
import {uploadImport,importState,previewImport} from '../src/lib/import-management';
import {commitImport} from '../src/lib/import-commit';
import {importLifecycle} from '../src/lib/import-lifecycle';
import {withTenant} from '../src/lib/db';
import {previewContactRemoval,removeCustomerContacts} from '../src/lib/customer-privacy';
import type {Actor} from '../src/lib/access';
const db=new pg.Client({connectionString:process.env.MIGRATION_DATABASE_URL});
let tenantId:string,foreignId:string,owner:Actor,storage:string;
beforeAll(()=>db.connect());afterAll(()=>db.end());
beforeEach(async()=>{
  storage=await mkdtemp(path.join(tmpdir(),'booking-import-test-'));vi.stubEnv('PRIVATE_STORAGE_DIR',storage);
  tenantId=randomUUID();foreignId=randomUUID();owner={id:randomUUID(),name:'Owner',email:randomUUID()+'@example.invalid',emailVerified:true,twoFactorEnabled:true,isPlatformAdmin:false};
  for(const id of [tenantId,foreignId])await db.query("INSERT INTO tenants(id,slug,name,address) VALUES($1,$2,'Import company','Test address')",[id,'import-'+id]);
  await db.query('INSERT INTO auth_user(id,name,email,email_verified,two_factor_enabled) VALUES($1,$2,$3,true,true)',[owner.id,owner.name,owner.email]);
  await db.query("INSERT INTO memberships(tenant_id,user_id,role) VALUES($1,$2,'owner')",[tenantId,owner.id]);
});
afterEach(async()=>{
  vi.unstubAllEnvs();
  for(const table of ['contact_removals','import_rows','import_batches','media','outbox','booking_management_tokens','booking_events','bookings','staff_services','services','service_groups','staff','access_audit_log','memberships'])await db.query('DELETE FROM '+table+' WHERE tenant_id=ANY($1::uuid[])',[[tenantId,foreignId]]);
  await db.query('DELETE FROM tenants WHERE id=ANY($1::uuid[])',[[tenantId,foreignId]]);await db.query('DELETE FROM auth_user WHERE id=$1',[owner.id]);
  if(path.dirname(storage)!==tmpdir()||!path.basename(storage).startsWith('booking-import-test-'))throw Error('Unsafe cleanup');await rm(storage,{recursive:true,force:true});
});
const input=()=>({tenantId,requestKey:randomUUID(),kind:'customers',delimiter:','});
it('blocks contact removal until import source copies have been purged',async()=>{
 const first=await prepared('customers','name,email\nImported Person,imported@example.invalid');
 await commitImport(owner,first);
 const customerId=(await db.query('SELECT id FROM customers WHERE tenant_id=$1',[tenantId])).rows[0].id;
 const initial=await previewContactRemoval(owner,tenantId,customerId);
 expect(initial).toMatchObject({canRemove:false,importSources:1});
 await expect(removeCustomerContacts(owner,{tenantId,customerId,fingerprint:initial.fingerprint,confirmed:true,identityConfirmed:true})).rejects.toMatchObject({code:'IMPORT_SOURCES_REMAIN'});
 await importLifecycle(owner,{tenantId,id:first.id,version:3,action:'discard-source',confirmed:true});
 const preview=await previewContactRemoval(owner,tenantId,customerId);expect(preview.canRemove).toBe(true);
 await removeCustomerContacts(owner,{tenantId,customerId,fingerprint:preview.fingerprint,confirmed:true,identityConfirmed:true});
 expect((await db.query('SELECT name,email FROM customers WHERE tenant_id=$1',[tenantId])).rows[0]).toEqual({name:'[removed]',email:null});
});
it('removes completed source copies while preserving imported records and external-ID duplicate checks',async()=>{
 const first=await prepared('customers','externalId,name,email\nold-123,Original Person,original@example.invalid');
 await commitImport(owner,first);
 const command={tenantId,id:first.id,version:3,action:'discard-source',confirmed:true};
 await expect(importLifecycle(owner,{...command,confirmed:undefined})).rejects.toMatchObject({code:'INVALID_INPUT'});
 await importLifecycle(owner,command);await importLifecycle(owner,command);
 const state=await importState(owner,tenantId,first.id);
 expect(state.batches[0].source_purged_at).toBeTruthy();expect(state.batches[0].headers).toEqual([]);
 expect(state.rows[0]).toMatchObject({source_values:[],normalized:{},status:'imported'});
 expect((await db.query('SELECT name,email FROM customers WHERE tenant_id=$1',[tenantId])).rows).toEqual([{name:'Original Person',email:'original@example.invalid'}]);
 expect((await db.query('SELECT status FROM media WHERE tenant_id=$1',[tenantId])).rows[0].status).toBe('deleted');
 const next=await prepared('customers','externalId,name,email\nold-123,Changed Person,new@example.invalid');
 expect((await importState(owner,tenantId,next.id)).rows[0].error_code).toContain('EXTERNAL_ID_IMPORTED');
 await expect(commitImport(owner,next)).rejects.toMatchObject({status:409});
});
async function prepared(kind:string,csv:string){
  const batch=await uploadImport(owner,{...input(),kind},csv);
  const headers=csv.split('\n')[0].split(',');
  await previewImport(owner,{tenantId,id:batch.id,version:1,mapping:Object.fromEntries(headers.map((h,i)=>[h,i])),timezone:'Europe/Tallinn',cutoverAt:'2030-01-01T00:00:00Z'});
  return {tenantId,id:batch.id,version:2,skipInvalid:false,skipDuplicates:false};
}
it('commits all four kinds, retries once and never sends an initial mail wave',async()=>{
  const customers=await prepared('customers','name,email\nFirst Person,same@example.invalid\nSecond Person,same@example.invalid');
  const results=await Promise.all([commitImport(owner,customers),commitImport(owner,customers)]);
  expect(results[0]).toEqual(results[1]);expect(results[0].imported).toBe(2);
  expect((await db.query('SELECT count(*)::int n FROM customers WHERE tenant_id=$1',[tenantId])).rows[0].n).toBe(2);
  const group=(await db.query("INSERT INTO service_groups(tenant_id,name) VALUES($1,'Imported') RETURNING id",[tenantId])).rows[0].id;
  await commitImport(owner,await prepared('services',`name,groupId,priceCents,duration\nImported service,${group},3500,60`));
  await commitImport(owner,await prepared('staff','name\nImported staff'));
  const service=(await db.query('SELECT id,online FROM services WHERE tenant_id=$1',[tenantId])).rows[0];
  const staff=(await db.query('SELECT id,online FROM staff WHERE tenant_id=$1',[tenantId])).rows[0];
  expect(service.online).toBe(false);expect(staff.online).toBe(false);
  await db.query('INSERT INTO staff_services(tenant_id,service_id,staff_id) VALUES($1,$2,$3)',[tenantId,service.id,staff.id]);
  const bookingCsv=`serviceId,staffId,name,email,startAt,priceCents,duration\n${service.id},${staff.id},First Person,same@example.invalid,2030-01-15T10:00:00+02:00,3500,60`;
  const booking=await prepared('bookings',bookingCsv);
  const conflicting=await prepared('bookings',bookingCsv.replace('First Person','Different Person'));
  expect((await commitImport(owner,booking)).imported).toBe(1);
  expect((await db.query('SELECT source,customer_notifications,is_test FROM bookings WHERE tenant_id=$1',[tenantId])).rows[0]).toEqual({source:'import',customer_notifications:false,is_test:false});
  expect((await db.query('SELECT count(*)::int n FROM outbox WHERE tenant_id=$1',[tenantId])).rows[0].n).toBe(0);
  await expect(commitImport(owner,conflicting)).rejects.toMatchObject({code:'IMPORT_OVERLAP'});
  expect((await importState(owner,tenantId,conflicting.id)).batches[0].status).toBe('preview');
  await previewImport(owner,{tenantId,id:conflicting.id,version:2,mapping:Object.fromEntries(bookingCsv.split('\n')[0].split(',').map((h,i)=>[h,i])),timezone:'Europe/Tallinn',cutoverAt:'2030-01-01T00:00:00Z'});
  expect((await importState(owner,tenantId,conflicting.id)).rows[0].error_code).toBe('BOOKING_OVERLAP');
  const enable={tenantId,id:booking.id,version:3,action:'enable-reminders'};
  await expect(importLifecycle(owner,enable)).rejects.toMatchObject({code:'REMINDER_POLICY_REQUIRED'});
  await db.query('UPDATE tenants SET reminder_minutes=1440,management_link_hours=24 WHERE id=$1',[tenantId]);
  expect(await importLifecycle(owner,enable)).toMatchObject({scheduled:1});
  expect(await importLifecycle(owner,enable)).toMatchObject({scheduled:0});
  const notices=(await db.query('SELECT kind,status,next_attempt_at FROM outbox WHERE tenant_id=$1',[tenantId])).rows;
  expect(notices).toHaveLength(1);expect(notices[0]).toMatchObject({kind:'booking.reminder',status:'pending'});
  expect(notices[0].next_attempt_at.getTime()).toBeGreaterThan(Date.now());
  expect((await db.query('SELECT customer_notifications FROM bookings WHERE tenant_id=$1',[tenantId])).rows[0].customer_notifications).toBe(true);
});
it('cancels unfinished imports, clears contacts and removes their private file idempotently',async()=>{
  const batch=await uploadImport(owner,input(),'name,email\nPrivate Person,private@example.invalid');
  const d={tenantId,id:batch.id,version:1,action:'cancel'};
  await importLifecycle(owner,d);await importLifecycle(owner,d);
  expect(await readdir(storage)).toHaveLength(0);
  const state=await importState(owner,tenantId,batch.id);
  expect(state.batches[0].status).toBe('cancelled');expect(state.rows[0].source_values).toEqual([]);
  expect((await db.query('SELECT status FROM media WHERE tenant_id=$1',[tenantId])).rows[0].status).toBe('deleted');
});
it('requires explicit skipping and rejects a duplicate completed after preview',async()=>{
  const csv='name,email\nFirst Person,same@example.invalid\nX,bad';
  const first=await prepared('customers',csv),second=await prepared('customers','name,email\nFirst Person,same@example.invalid');
  await expect(commitImport(owner,first)).rejects.toMatchObject({code:'IMPORT_REVIEW_REQUIRED'});
  expect((await db.query('SELECT count(*)::int n FROM customers WHERE tenant_id=$1',[tenantId])).rows[0].n).toBe(0);
  expect(await commitImport(owner,{...first,skipInvalid:true})).toMatchObject({imported:1,rejected:1});
  await expect(commitImport(owner,second)).rejects.toMatchObject({code:'IMPORT_CHANGED'});
});
it('normalizes mapped rows, flags duplicates and validates preview versions',async()=>{
  const batch=await uploadImport(owner,input(),'Client,Email\n  First Person ,same@example.invalid\nSecond Person,same@example.invalid\nSecond Person,same@example.invalid\nX,bad-email');
  const d={tenantId,id:batch.id,version:1,mapping:{name:0,email:1},timezone:'Europe/Tallinn',cutoverAt:'2030-01-01T00:00:00Z'};
  expect(await previewImport(owner,d)).toMatchObject({version:2,errors:1,warnings:1});
  const state=await importState(owner,tenantId,batch.id);
  expect(state.rows[0].normalized).toMatchObject({name:'First Person',email:'same@example.invalid'});
  expect(state.rows[1].warning_codes).toEqual([]);
  expect(state.rows[2].warning_codes).toEqual(['DUPLICATE_ROW']);
  expect(state.rows[3].error_code).toContain('FIELD_email');
  await expect(previewImport(owner,d)).rejects.toMatchObject({code:'VERSION_CONFLICT'});
  await expect(previewImport(owner,{...d,version:2,mapping:{name:0,email:0}})).rejects.toMatchObject({code:'IMPORT_MAPPING'});
});
it('deduplicates concurrent uploads, preserves separate same-email rows and paginates previews',async()=>{
  const d=input(),csv='name,email\n'+Array.from({length:601},(_,i)=>`Person ${i},shared@example.invalid`).join('\n');
  const [first,second]=await Promise.all([uploadImport(owner,d,csv),uploadImport(owner,d,csv)]);
  expect(first.id).toBe(second.id);expect(await readdir(storage)).toHaveLength(1);
  const state=await importState(owner,tenantId,first.id);expect(state.batches[0]).toMatchObject({total_rows:601,status:'uploaded',kind:'customers'});
  expect(state.rows).toHaveLength(100);expect(state.nextAfter).toBe(101);
  expect((await importState(owner,tenantId,first.id,601)).rows[0]).toMatchObject({row_number:602,source_values:['Person 600','shared@example.invalid']});
  await expect(uploadImport(owner,d,csv+'\nAnother,other@example.invalid')).rejects.toMatchObject({code:'IDEMPOTENCY_MISMATCH'});
  expect((await db.query('SELECT count(*)::int n FROM customers WHERE tenant_id=$1',[tenantId])).rows[0].n).toBe(0);
  expect((await db.query('SELECT count(*)::int n FROM outbox WHERE tenant_id=$1',[tenantId])).rows[0].n).toBe(0);
});
it('enforces current owner rights and tenant isolation',async()=>{
  const batch=await uploadImport(owner,input(),'name,email\nOwner,owner@example.invalid');
  await withTenant(foreignId,async c=>expect((await c.query('SELECT * FROM import_rows WHERE batch_id=$1',[batch.id])).rowCount).toBe(0));
  await expect(importState(owner,foreignId,batch.id)).rejects.toMatchObject({status:403});
  await db.query("UPDATE memberships SET role='receptionist' WHERE tenant_id=$1",[tenantId]);
  await expect(importState(owner,tenantId,batch.id)).rejects.toMatchObject({status:403});
  await expect(uploadImport(owner,input(),'name\nAnother')).rejects.toMatchObject({status:403});
  expect(await readdir(storage)).toHaveLength(1);
});
it('keeps row-level shape errors but rejects malformed files before storage',async()=>{
  await expect(uploadImport(owner,input(),'name,name\na,b')).rejects.toMatchObject({code:'CSV_HEADERS'});
  expect(await readdir(storage)).toHaveLength(0);
  const batch=await uploadImport(owner,input(),'name,email\nOnly name');
  expect((await importState(owner,tenantId,batch.id)).rows[0]).toMatchObject({error_code:'CSV_ROW_WIDTH',source_values:['Only name']});
});
