"use client";
import {useEffect,useRef,useState,type FormEvent} from 'react';
import type {AdminBookingsState,BookingAvailability,BookingDetail,BookingHistoryItem,BookingPolicy} from '@/lib/booking-management-contracts';
import type {Offer} from '@/lib/contracts';
import {useBookingMutation} from './use-booking-mutation';
const statusNames:Record<string,string>={confirmed:'Kinnitatud',cancelled:'Tühistatud',completed:'Teenindatud',no_show:'Ei ilmunud'};
const eventNames:Record<string,string>={'booking.created':'Broneering loodud','booking.cancel':'Broneering tühistatud','booking.reschedule':'Broneering muudetud','booking.status':'Seisund parandatud','attention.required':'Vajab lahendamist','link.issued':'Uus halduslink väljastatud','link.revoked':'Halduslink tühistatud'};
const money=(value:number)=>new Intl.NumberFormat('et-EE',{style:'currency',currency:'EUR'}).format(value/100);
const moment=(value:string,zone:string)=>new Intl.DateTimeFormat('et-EE',{dateStyle:'medium',timeStyle:'short',timeZone:zone}).format(new Date(value));
function historySummary(value:Record<string,unknown>,zone:string){return [value.serviceName,value.staffName,typeof value.start==='string'?moment(value.start,zone):null,typeof value.price==='number'?money(value.price):null,typeof value.duration==='number'?value.duration+' min':null,typeof value.status==='string'?statusNames[value.status]:null].filter(Boolean).join(' · ');}
async function read(query:Record<string,string>,signal?:AbortSignal){const response=await fetch('/api/admin/bookings?'+new URLSearchParams(query),{cache:'no-store',signal});const body=await response.json();if(!response.ok)throw new Error(body.error||'Broneeringute laadimine ebaõnnestus.');return body;}
type EditorProps={tenantId:string;state:AdminBookingsState;locked:boolean;submit:(payload?:unknown)=>Promise<void>};
export default function BookingManagement({tenantId,userId}:{tenantId:string;userId:string}){
  const [state,setState]=useState<AdminBookingsState|null>(null),[day,setDay]=useState(()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Tallinn'}).format(new Date())),[attention,setAttention]=useState(false),[selected,setSelected]=useState(''),[creating,setCreating]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[revision,setRevision]=useState(0),[page,setPage]=useState(0);
  const initialDay=useRef(false);
  const mutation=useBookingMutation('admin:'+tenantId+':'+userId,'/api/admin/bookings'),locked=mutation.locked||loading,booking=state?.bookings.find(item=>item.id===selected);
  useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');read({view:'list',tenantId,day,attention:attention?'1':'0',page:String(page)},controller.signal).then(body=>{if(!controller.signal.aborted){if(!initialDay.current){initialDay.current=true;if(body.today!==day){setDay(body.today);return;}}setState(body);}}).catch(error=>{if(!controller.signal.aborted){setState(null);setError(error instanceof Error?error.message:'Laadimine ebaõnnestus.');}}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[tenantId,day,attention,revision,page]);
  useEffect(()=>{if(['VERSION_CONFLICT','CUTOFF_PASSED','SLOT_UNAVAILABLE','OFFER_CHANGED','RULES_CHANGED'].includes(mutation.code))setRevision(value=>value+1);},[mutation.code]);
  async function submit(payload?:unknown){const result=await mutation.send(payload);if(result){setNotice(result.currentVersion?'Toiming oli salvestatud, kuid broneeringut on pärast seda muudetud. Värskendasime loendi; ava kehtiv detail.':'Salvestatud: '+result.reference+' · '+(statusNames[result.status]||result.status)+'.');setCreating(false);if(!attention&&!result.currentVersion&&state){setDay(new Intl.DateTimeFormat('sv-SE',{timeZone:state.timezone}).format(new Date(result.start)));setPage(0);setSelected(result.id);}setRevision(value=>value+1);}}
  const managementUrl=mutation.result?.managementUrl&&state?.publicHostname?`${state.publicHostname.endsWith('.localhost')?'http':'https'}://${state.publicHostname}${state.publicHostname.endsWith('.localhost')&&window.location.port?':'+window.location.port:''}${mutation.result.managementUrl}`:null;
  return <section aria-labelledby="bookings-heading"><h2 id="bookings-heading">Broneeringud</h2>
    <p><label>Kuupäev <input type="date" value={day} disabled={locked||attention} onChange={event=>{setDay(event.target.value);setSelected('');setPage(0);}}/></label> <label><input type="checkbox" checked={attention} disabled={locked} onChange={event=>{setAttention(event.target.checked);setSelected('');setPage(0);}}/> Lahendamist ootavad tulevased broneeringud</label></p>
    <p><button type="button" disabled={locked} onClick={()=>{setCreating(true);setSelected('');setNotice('');}}>Lisa broneering käsitsi</button> <button type="button" disabled={locked} onClick={()=>setRevision(value=>value+1)}>Värskenda broneeringuid</button></p>
    {loading&&<p role="status">Laadime broneeringuid…</p>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{mutation.error&&<p role="alert">{mutation.error}</p>}{mutation.saving&&<p role="status">Salvestame broneeringut…</p>}{mutation.uncertain&&<p role="alert">Eelmise toimingu tulemus vajab kontrollimist. <button type="button" onClick={()=>submit()}>Kontrolli sama toimingu tulemust</button></p>}
    {mutation.result?.managementUrl&&<aside><h3>Kliendi halduslink</h3>{managementUrl?<p><a href={managementUrl} target="_blank" rel="noopener noreferrer">Ava kliendi halduslink</a><br/><input aria-label="Kliendiga jagatav halduslink" readOnly value={managementUrl} onFocus={event=>event.target.select()}/></p>:<p>Ettevõttel puudub kasutusvalmis avalik domeen.</p>}<p>Jaga ainult selle broneeringu kliendiga. Uue lingi loomine tühistab eelmise lingi.</p></aside>}
    {state&&<>{!loading&&!state.bookings.length&&<p>{attention?'Lahendamist ootavaid broneeringuid pole.':'Sel päeval broneeringuid pole.'}</p>}
      <ul aria-label="Broneeringute loend">{state.bookings.map(item=><li key={item.id}><button type="button" disabled={locked} aria-pressed={item.id===selected} onClick={()=>{setSelected(item.id);setCreating(false);}}>{moment(item.start,state.timezone)} · {item.name} · {item.serviceName} · {item.staffName} · {statusNames[item.status]}{item.attentionReason?' · Vajab lahendamist':''}</button></li>)}</ul>
      <p>Lehekülg {page+1} (kuni 100 broneeringut). <button type="button" disabled={locked||page===0} onClick={()=>{setSelected('');setPage(value=>value-1);}}>Eelmine lehekülg</button> <button type="button" disabled={locked||!state.hasMore||page>=10000} onClick={()=>{setSelected('');setPage(value=>value+1);}}>Järgmine lehekülg</button></p>
      {creating&&<OfferForm key="create" refresh={revision} tenantId={tenantId} state={state} locked={locked} submit={submit} close={()=>setCreating(false)}/>}
      {booking&&<BookingEditor key={booking.id+':'+booking.version+':'+revision} tenantId={tenantId} state={state} booking={booking} locked={locked} submit={submit}/>}
      <PolicyForm key={state.policy.version} tenantId={tenantId} policy={state.policy} locked={locked} reload={()=>setRevision(value=>value+1)}/>
    </>}
  </section>;
}
function BookingEditor({tenantId,state,booking,locked,submit}:EditorProps&{booking:BookingDetail}){
  const [mode,setMode]=useState<'view'|'cancel'|'reschedule'|'status'|'revoke'>('view'),[reason,setReason]=useState(''),[override,setOverride]=useState(false),[status,setStatus]=useState('completed'),[events,setEvents]=useState<BookingHistoryItem[]|null>(null),[historyError,setHistoryError]=useState('');
  useEffect(()=>{const controller=new AbortController();read({view:'history',tenantId,bookingId:booking.id},controller.signal).then(body=>{if(!controller.signal.aborted)setEvents(body.events);}).catch(error=>{if(!controller.signal.aborted)setHistoryError(error instanceof Error?error.message:'Ajalugu ei saanud laadida.');});return()=>controller.abort();},[tenantId,booking.id,booking.version]);
  const base={tenantId,bookingId:booking.id,version:booking.version},canChange=booking.status==='confirmed'&&(booking.canChange||state.canOverride);
  return <article><h3>{booking.reference} · {statusNames[booking.status]}</h3>
    <dl><dt>Klient</dt><dd>{booking.name}</dd><dt>Kontakt</dt><dd>{booking.email?<a href={'mailto:'+booking.email}>{booking.email}</a>:'E-post puudub'}{booking.phone&&<> · <a href={'tel:'+booking.phone.replace(/[^+\d]/g,'')}>{booking.phone}</a></>}</dd><dt>Teenus ja töötaja</dt><dd>{booking.serviceName} · {booking.staffName}</dd><dt>Aeg</dt><dd>{moment(booking.start,state.timezone)} – {moment(booking.end,state.timezone)}</dd><dt>Kokkulepitud hind ja kestus</dt><dd>{money(booking.price)} · {booking.duration} min</dd><dt>Päritolu</dt><dd>{booking.source==='manual'?'Käsitsi lisatud':'Veebist broneeritud'}</dd></dl>
    {booking.attentionReason&&<p role="status">Vajab lahendamist: {booking.attentionReason}. Vana aeg on alles. Lepi kliendiga uus aeg kokku või tühista broneering.</p>}
    <p>{booking.deadline?'Muutmise ja tühistamise tähtaeg: '+moment(booking.deadline,state.timezone)+'.':'Varasemad muutmistingimused puuduvad.'} {!booking.canChange&&booking.status==='confirmed'?'Tähtajajärgne muudatus nõuab volitatud haldaja erandit ja põhjendust.':''}</p><p>{booking.notice}</p><p>Uue halduslingi väljastamine muudab varasema lingi kehtetuks.</p>
    {mode==='view'&&<p><button type="button" disabled={locked||!canChange} onClick={()=>setMode('reschedule')}>Muuda broneeringut</button> <button type="button" disabled={locked||!canChange} onClick={()=>setMode('cancel')}>Tühista broneering</button> <button type="button" disabled={locked||booking.status==='cancelled'} onClick={()=>setMode('status')}>Muuda seisundit</button> <button type="button" disabled={locked||state.policy.linkHours===null||Date.parse(booking.end)+(state.policy.linkHours??0)*3600000<=Date.now()} onClick={()=>submit({...base,action:'issue-link'})}>Loo uus halduslink</button> <button type="button" disabled={locked} onClick={()=>setMode('revoke')}>Tühista halduslink</button></p>}
    {mode==='reschedule'&&<OfferForm tenantId={tenantId} state={state} booking={booking} locked={locked} submit={submit} close={()=>setMode('view')}/>}
    {['cancel','status','revoke'].includes(mode)&&<form onSubmit={event=>{event.preventDefault();void submit({...base,action:mode==='revoke'?'revoke-link':mode,reason,...(mode==='cancel'?{overrideDeadline:override}:mode==='status'?{status}:{})});}}><h4>{mode==='cancel'?'Kinnita broneeringu tühistamine':mode==='revoke'?'Kinnita halduslingi tühistamine':'Paranda broneeringu seisund'}</h4>
      {mode==='status'&&<label>Uus seisund <select value={status} disabled={locked} onChange={event=>setStatus(event.target.value)}><option value="completed">Teenindatud</option><option value="no_show">Ei ilmunud</option><option value="confirmed">Kinnitatud</option></select></label>}
      <label>Põhjus {mode==='cancel'&&booking.canChange?'(soovi korral)':''}<textarea value={reason} maxLength={500} minLength={mode==='cancel'&&booking.canChange?0:3} required={mode!=='cancel'||!booking.canChange} disabled={locked} onChange={event=>setReason(event.target.value)}/></label>
      {mode==='cancel'&&!booking.canChange&&state.canOverride&&<label><input type="checkbox" checked={override} required disabled={locked} onChange={event=>setOverride(event.target.checked)}/> Luban põhjendatud erandi pärast tähtaega</label>}
      <p>{mode==='cancel'?'Broneeritud aeg vabastatakse pärast serveri kinnitust.':mode==='revoke'?'Olemasolev link kaotab kehtivuse; broneering jääb alles.':'Teenindatuks või mitteilmunuks saab märkida pärast broneeritud aja lõppu.'}</p><button disabled={locked}>Kinnita toiming</button> <button type="button" disabled={locked} onClick={()=>setMode('view')}>Loobu</button></form>}
    <details><summary>Muudatuste ajalugu</summary>{historyError&&<p role="alert">{historyError}</p>}{events===null&&!historyError&&<p>Laadime ajalugu…</p>}<ol>{events?.map((event,index)=><li key={event.at+':'+index}>{moment(event.at,state.timezone)} · {event.actorName||'Klient / süsteem'} · {eventNames[event.action]||'Broneeringu sündmus'}{event.reason?' · '+event.reason:''}<details><summary>Broneering enne ja pärast</summary>{event.before&&<p>Enne: {historySummary(event.before,state.timezone)}</p>}<p>Pärast: {historySummary(event.after,state.timezone)}</p></details></li>)}</ol>{events?.length===100&&<p>Näidatakse 100 viimast muudatust.</p>}</details>
  </article>;
}
function OfferForm({tenantId,state,booking,locked,submit,close,refresh=0}:EditorProps&{booking?:BookingDetail;refresh?:number;close:()=>void}){
  const [serviceId,setServiceId]=useState(booking?.serviceId??state.services[0]?.id??''),[staffId,setStaffId]=useState(booking?.staffId??''),[day,setDay]=useState(state.today),[offers,setOffers]=useState<Offer[]>([]),[offer,setOffer]=useState<Offer|null>(null),[rulesVersion,setRulesVersion]=useState(state.rulesVersion),[loading,setLoading]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(0),[name,setName]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[reason,setReason]=useState(''),[override,setOverride]=useState(false);
  const workers=state.staff.filter(worker=>state.assignments.some(a=>a.staffId===worker.id&&a.serviceId===serviceId));
  useEffect(()=>{if(!workers.some(worker=>worker.id===staffId))setStaffId(workers[0]?.id??'');},[serviceId,state.staff,state.assignments,staffId]);
  useEffect(()=>{setOffer(null);setOffers([]);setError('');if(!serviceId||!staffId)return;const controller=new AbortController();setLoading(true);read({view:'offers',tenantId,serviceId,staffId,day,...(booking?{bookingId:booking.id}:{})},controller.signal).then((body:BookingAvailability)=>{if(!controller.signal.aborted){setOffers(body.offers);setRulesVersion(body.rulesVersion);}}).catch(error=>{if(!controller.signal.aborted)setError(error instanceof Error?error.message:'Aegu ei saanud laadida.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[tenantId,serviceId,staffId,day,booking?.id,retry,state.rulesVersion,refresh]);
  return <form onSubmit={event=>{event.preventDefault();if(!offer)return;void submit({tenantId,action:booking?'reschedule':'manual-create',serviceId:offer.serviceId,staffId:offer.staffId,start:offer.start,expectedPrice:offer.price,expectedDuration:offer.duration,expectedRulesVersion:rulesVersion,...(booking?{bookingId:booking.id,version:booking.version,reason,overrideDeadline:override}:{name,email:email.trim()||null,phone})});}}><h3>{booking?'Vali uus pakkumine':'Lisa broneering käsitsi'}</h3>
    <label>Teenus <select value={serviceId} required disabled={locked} onChange={event=>{setOffer(null);setServiceId(event.target.value);}}><option value="">Vali teenus</option>{state.services.map(service=><option key={service.id} value={service.id}>{service.name}{service.online?'':' (ainult halduses)'}</option>)}</select></label>
    <label>Töötaja <select value={staffId} required disabled={locked} onChange={event=>{setOffer(null);setStaffId(event.target.value);}}><option value="">Vali töötaja</option>{workers.map(worker=><option key={worker.id} value={worker.id}>{worker.name}</option>)}</select></label>
    <label>Kuupäev <input type="date" value={day} min={state.today} max={state.maxDate} required disabled={locked} onChange={event=>{setOffer(null);setDay(event.target.value);}}/></label>
    {loading&&<p role="status">Laadime vabu aegu…</p>}{error&&<p role="alert">{error} <button type="button" disabled={locked} onClick={()=>setRetry(value=>value+1)}>Proovi uuesti</button></p>}{!loading&&!error&&serviceId&&staffId&&!offers.length&&<p>Sel päeval vabu aegu pole.</p>}
    <ul aria-label="Haldaja vabad ajad">{!loading&&offers.map(item=><li key={item.start}><button type="button" aria-pressed={item===offer} disabled={locked} onClick={()=>setOffer(item)}>{moment(item.start,state.timezone)} · {item.duration} min · {money(item.price)}</button></li>)}</ul>
    {!booking&&<><label>Kliendi nimi <input value={name} required minLength={2} maxLength={120} disabled={locked} onChange={event=>setName(event.target.value)}/></label><label>E-post (soovi korral) <input type="email" value={email} maxLength={254} disabled={locked} onChange={event=>setEmail(event.target.value)}/></label><label>Telefon (soovi korral) <input type="tel" value={phone} maxLength={30} disabled={locked} onChange={event=>setPhone(event.target.value)}/></label>{!email.trim()&&<p>E-postita broneeringule kinnituskirja ei saadeta. Anna aeg ja tingimused kliendile ise edasi.</p>}</>}
    {booking&&<label>Muudatuse põhjus {booking.canChange?'(soovi korral)':''}<textarea value={reason} maxLength={500} required={!booking.canChange} minLength={booking.canChange?0:3} disabled={locked} onChange={event=>setReason(event.target.value)}/></label>}
    {booking&&!booking.canChange&&state.canOverride&&<label><input type="checkbox" checked={override} required disabled={locked} onChange={event=>setOverride(event.target.checked)}/> Luban põhjendatud erandi pärast tähtaega</label>}
    {offer&&<aside><h4>Kinnita pakkumine</h4><p>{state.services.find(service=>service.id===offer.serviceId)?.name} · {offer.staffName} · {moment(offer.start,state.timezone)} – {moment(offer.end,state.timezone)} · {offer.duration} min · {money(offer.price)}</p><p>Muutmine ja tühistamine: vähemalt {booking?booking.cancellationHours??'teadmata':state.cancellationHours} tundi enne algust. {booking?'Vana aeg jääb alles kuni uue aja kinnitamiseni.':''}</p></aside>}
    <button disabled={locked||loading||!offer}>{booking?'Kinnita uus aeg ja hind':'Kinnita käsitsi broneering'}</button> <button type="button" disabled={locked} onClick={close}>Loobu</button>
  </form>;
}
function PolicyForm({tenantId,policy,locked,reload}:{tenantId:string;policy:BookingPolicy;locked:boolean;reload:()=>void}){
  const [enabled,setEnabled]=useState(policy.linkHours!==null),[hours,setHours]=useState(policy.linkHours===null?'':String(policy.linkHours)),[email,setEmail]=useState(policy.contactEmail),[phone,setPhone]=useState(policy.contactPhone),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
  async function save(event:FormEvent){event.preventDefault();if(saving||locked)return;setSaving(true);setMessage('');try{const response=await fetch('/api/admin/booking-policy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tenantId,version:policy.version,contactEmail:email.trim(),contactPhone:phone.trim(),linkHours:enabled?Number(hours):null})});const body=await response.json();if(!response.ok)throw new Error(body.error||'Seadete salvestamine ebaõnnestus.');reload();}catch(error){setMessage(error instanceof Error?error.message:'Seadete salvestamine ebaõnnestus.');}finally{setSaving(false);}}
  return <details><summary>Ettevõtte kontakt ja halduslinkide poliitika</summary><p>Poliitika määrab ettevõtte omanik. Kehtivus arvestatakse broneeritud aja lõpust. Olemasolevad lingid säilitavad neile määratud kehtivusreegli; uue lingi loomine tühistab sama broneeringu eelmise lingi.</p><form onSubmit={save}><fieldset disabled={locked||saving||!policy.canEdit}><label>Avalik e-post <input type="email" value={email} maxLength={254} onChange={event=>setEmail(event.target.value)}/></label><label>Avalik telefon <input type="tel" value={phone} maxLength={30} onChange={event=>setPhone(event.target.value)}/></label><label><input type="checkbox" checked={enabled} onChange={event=>setEnabled(event.target.checked)}/> Luba uute kliendi halduslinkide väljastamine</label>{enabled&&<label>Kehtivus tundides pärast broneeringu lõppu <input type="number" min={0} max={8760} step={1} required value={hours} onChange={event=>setHours(event.target.value)}/></label>}{policy.canEdit&&<button>Salvesta ettevõtte poliitika</button>}</fieldset></form>{message&&<p role="alert">{message} <button type="button" disabled={saving||locked} onClick={reload}>Laadi seaded uuesti</button></p>}</details>;
}
