"use client";
import {translator,type Translate} from '@/lib/i18n';
import {localeTags,locales,localeNames,type Locale} from '@/lib/locales';
import {localizedFetch as fetch} from '@/lib/client-fetch';
import {useI18n} from '@/components/i18n-provider';

import {useEffect,useRef,useState,type FormEvent} from 'react';
import type {AdminBookingsState,BookingAvailability,BookingDetail,BookingHistoryItem,BookingPolicy} from '@/lib/booking-management-contracts';
import type {Offer} from '@/lib/contracts';
import AdminCalendar from './admin-calendar';
import {DateTime} from 'luxon';
import {useBookingMutation} from './use-booking-mutation';
const statusNames:Record<string,string>={confirmed:'Kinnitatud',cancelled:'Tühistatud',completed:'Teenindatud',no_show:'Ei ilmunud'};
const eventNames:Record<string,string>={'booking.created':'Broneering loodud','booking.cancel':'Broneering tühistatud','booking.reschedule':'Broneering muudetud','booking.status':'Seisund parandatud','attention.required':'Vajab lahendamist','link.issued':'Uus halduslink väljastatud','link.revoked':'Halduslink tühistatud'};
function historySummary(value:Record<string,unknown>,zone:string,locale:Locale){const t=translator(locale);const moment=(v:string,z:string)=>new Intl.DateTimeFormat(localeTags[locale],{dateStyle:'medium',timeStyle:'short',timeZone:z}).format(new Date(v));const money=(v:number)=>new Intl.NumberFormat(localeTags[locale],{style:'currency',currency:'EUR'}).format(v/100);return [value.serviceName,value.staffName,typeof value.start==='string'?moment(value.start,zone):null,typeof value.price==='number'?money(value.price):null,typeof value.duration==='number'?value.duration+t(' min'):null,typeof value.status==='string'?t(statusNames[value.status]):null].filter(Boolean).join(' · ');}
async function read(query:Record<string,string>,signal?:AbortSignal){const response=await fetch('/api/admin/bookings?'+new URLSearchParams(query),{cache:'no-store',signal});const body=await response.json();if(!response.ok)throw Object.assign(new Error(body.error||'Broneeringute laadimine ebaõnnestus.'),{status:response.status});return body;}
type EditorProps={tenantId:string;state:AdminBookingsState;locked:boolean;submit:(payload?:unknown)=>Promise<void>};
export default function BookingManagement({tenantId,userId}:{tenantId:string;userId:string}){
  const {t,locale}=useI18n();
  const money=(value:number)=>new Intl.NumberFormat(localeTags[locale],{style:'currency',currency:'EUR'}).format(value/100);
  const moment=(value:string,zone:string)=>new Intl.DateTimeFormat(localeTags[locale],{dateStyle:'medium',timeStyle:'short',timeZone:zone}).format(new Date(value));

  const [state,setState]=useState<AdminBookingsState|null>(null),[day,setDay]=useState(()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Tallinn'}).format(new Date())),[attention,setAttention]=useState(false),[selected,setSelected]=useState(''),[creating,setCreating]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[revision,setRevision]=useState(0),[page,setPage]=useState(0);
  const [view,setView]=useState<'list'|'day'|'week'>('day'),[staffFilter,setStaffFilter]=useState(''),[lastUpdated,setLastUpdated]=useState(''),[offline,setOffline]=useState(false),[editor,setEditor]=useState<BookingDetail|null>(null),[createContext,setCreateContext]=useState<{day:string;staffId:string}|null>(null);
  const initialDay=useRef(false);

  const mutation=useBookingMutation('admin:'+tenantId+':'+userId,'/api/admin/bookings'),locked=mutation.locked||loading||offline,booking=editor;
  useEffect(()=>{
    let disposed=false,running=false,controller:AbortController|undefined;
    setState(null);setLoading(true);setError('');setLastUpdated('');
    async function refresh(){
      if(running||disposed)return;
      running=true;controller=new AbortController();const timeout=setTimeout(()=>controller?.abort(),8000);
      try{
        const body:AdminBookingsState=await read({view:'list',tenantId,day,mode:view,attention:attention?'1':'0',page:String(page),...(staffFilter?{staffId:staffFilter}:{})},controller.signal);
        if(disposed)return;
        if(!initialDay.current){initialDay.current=true;if(body.today!==day){setDay(body.today);return;}}
        setState(body);setLastUpdated(new Date().toISOString());setOffline(false);setError('');
      }catch(error){if(!disposed){if(error&&typeof error==='object'&&'status' in error&&[401,403,404].includes(Number(error.status))){setState(null);setEditor(null);setCreating(false);}setOffline(true);setError(error instanceof Error&&!['AbortError','TypeError'].includes(error.name)?error.message:t("Serveriga ühendus puudub või vastus viibib."));}}
      finally{clearTimeout(timeout);running=false;if(!disposed)setLoading(false);}
    }
    void refresh();
    const timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh();},5000);
    const online=()=>void refresh(),lost=()=>setOffline(true),visible=()=>{if(document.visibilityState==='visible')void refresh();};
    window.addEventListener('online',online);window.addEventListener('offline',lost);document.addEventListener('visibilitychange',visible);
    return()=>{disposed=true;controller?.abort();clearInterval(timer);window.removeEventListener('online',online);window.removeEventListener('offline',lost);document.removeEventListener('visibilitychange',visible);};
  },[tenantId,day,attention,revision,page,view,staffFilter]);
  useEffect(()=>{if(['VERSION_CONFLICT','CUTOFF_PASSED','SLOT_UNAVAILABLE','OFFER_CHANGED','RULES_CHANGED'].includes(mutation.code))setRevision(value=>value+1);},[mutation.code]);
  async function submit(payload?:unknown){const result=await mutation.send(payload);if(result){setNotice(result.currentVersion?t("Toiming oli salvestatud, kuid broneeringut on pärast seda muudetud. Värskendasime loendi; ava kehtiv detail."):t("Salvestatud: ")+result.reference+' · '+(t(statusNames[result.status])||result.status)+'.');setCreating(false);setEditor(null);if(!attention&&!result.currentVersion&&state){setDay(new Intl.DateTimeFormat('sv-SE',{timeZone:state.timezone}).format(new Date(result.start)));setPage(0);setSelected(result.id);}setRevision(value=>value+1);}}
  const managementUrl=mutation.result?.managementUrl&&state?.publicHostname?`${state.publicHostname.endsWith('.localhost')?'http':'https'}://${state.publicHostname}${state.publicHostname.endsWith('.localhost')&&window.location.port?':'+window.location.port:''}${mutation.result.managementUrl}`:null;
  return <section aria-labelledby="bookings-heading"><h2 id="bookings-heading">{t("Broneeringud")}</h2>
    <p><label>{t("Vaade ")}<select value={view} disabled={locked||attention} onChange={e=>{if(e.target.value==='week'&&!staffFilter)setStaffFilter(state?.selectedStaffId||state?.staff[0]?.id||'');setView(e.target.value as typeof view);setPage(0);}}><option value="day">{t("Päev")}</option><option value="week">{t("Nädal")}</option><option value="list">{t("Nimekiri")}</option></select></label> <label>{t("Töötaja ")}<select value={staffFilter||state?.selectedStaffId||''} disabled={locked} onChange={e=>{setStaffFilter(e.target.value);setPage(0);}}>{view!=='week'&&<option value="">{t("Kõik lubatud töötajad")}</option>}{state?.staff.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></p>
    <p><label>{t("Kuupäev ")}<input type="date" value={day} disabled={locked||attention} onChange={event=>{setDay(event.target.value);setSelected('');setEditor(null);setPage(0);}}/></label> <label><input type="checkbox" checked={attention} disabled={locked} onChange={event=>{setAttention(event.target.checked);setSelected('');setPage(0);}}/> {t("Lahendamist ootavad tulevased broneeringud")}</label></p>
    <p><button type="button" disabled={locked} onClick={()=>{setCreating(true);setEditor(null);setCreateContext({day,staffId:staffFilter||state?.selectedStaffId||''});setSelected('');setNotice('');}}>{t("Lisa broneering käsitsi")}</button> <button type="button" disabled={mutation.locked||loading} onClick={()=>setRevision(value=>value+1)}>{t("Värskenda broneeringuid")}</button></p>
    <p>{lastUpdated?t("Viimati uuendatud: ")+new Date(lastUpdated).toLocaleTimeString(localeTags[locale],{timeZone:state?.timezone||'Europe/Tallinn'}):t("Andmed pole veel laaditud.")} {t("Aktiivset vaadet värskendatakse iga 5 sekundi järel.")}</p>
    {offline&&<p role="alert">{t("Ühendus serveriga pole kinnitatud. Kuvatud andmed võivad olla aegunud; muudatusi ei saa salvestada.")}</p>}
    {booking&&state&&state.bookings.some(b=>b.id===booking.id&&b.version!==booking.version)&&<p role="alert">{t("Broneeringut on vahepeal muudetud. Sinu vorm säilis. ")}<button type="button" disabled={locked} onClick={()=>setEditor(state.bookings.find(b=>b.id===booking.id)??null)}>{t("Ava uus versioon")}</button></p>}
    {booking&&state&&!state.bookings.some(b=>b.id===booking.id)&&<p role="alert">{t("Avatud broneering ei kuulu enam sellesse loendisse. Kontrolli kuupäeva, töötajafiltrit ja lehekülge; salvestamisel kontrollitakse kehtivat versiooni.")}</p>}
    {loading&&<p role="status">{t("Laadime broneeringuid…")}</p>}{error&&<p role="alert">{t(error)}</p>}{notice&&<p role="status">{t(notice)}</p>}{mutation.error&&<p role="alert">{t(mutation.error)}</p>}{mutation.saving&&<p role="status">{t("Salvestame broneeringut…")}</p>}{mutation.uncertain&&<p role="alert">{t("Eelmise toimingu tulemus vajab kontrollimist. ")}<button type="button" onClick={()=>submit()}>{t("Kontrolli sama toimingu tulemust")}</button></p>}
    {mutation.result?.managementUrl&&<aside><h3>{t("Kliendi halduslink")}</h3>{managementUrl?<p><a href={managementUrl} target="_blank" rel={"noopener noreferrer"}>{t("Ava kliendi halduslink")}</a><br/><input aria-label={t("Kliendiga jagatav halduslink")} readOnly value={managementUrl} onFocus={event=>event.target.select()}/></p>:<p>{t("Ettevõttel puudub kasutusvalmis avalik domeen.")}</p>}<p>{t("Jaga ainult selle broneeringu kliendiga. Uue lingi loomine tühistab eelmise lingi.")}</p></aside>}
    {state&&<>
      {state.metrics&&<p>{t("Valitud vahemik ja töötajafilter: ")}{state.metrics.total} {t("broneeringut, ")}{state.metrics.completed} {t("teenindatud, ")}{state.metrics.cancelled} {t("tühistatud. Tühistamata teenuste hinnakirjaline väärtus: ")}{money(state.metrics.value)} {t("(ei ole tegelik käive).")}</p>}
      {!attention&&view!=='list'&&<><AdminCalendar state={state} locked={locked} select={b=>{setEditor(b);setSelected(b.id);setCreating(false);}} create={(day,staffId)=>{setCreateContext({day,staffId});setCreating(true);setEditor(null);}}/><p>{t("Telefonis kasuta allolevat nimekirja. Kalender näitab selle lehekülje tühistamata broneeringuid; tööaeg ei tähenda vaba broneeritavat aega.")}</p></>}
      {!loading&&!state.bookings.length&&<p>{attention?t("Lahendamist ootavaid broneeringuid pole."):t("Valitud vahemikus broneeringuid pole.")}</p>}
      <ul aria-label={t("Broneeringute loend")}>{state.bookings.map(item=><li key={item.id}><button type="button" disabled={locked} aria-pressed={item.id===selected} onClick={()=>{setSelected(item.id);setEditor(item);setCreating(false);}}>{moment(item.start,state.timezone)} · {item.name} · {item.serviceName} · {item.staffName} · {t(statusNames[item.status])}{item.attentionReason?t(" · Vajab lahendamist"):''}</button></li>)}</ul>
      <p>{t("Lehekülg ")}{page+1} {t("(kuni ")}{state.pageSize??100} {t("broneeringut). ")}<button type="button" disabled={locked||page===0} onClick={()=>{setSelected('');setPage(value=>value-1);}}>{t("Eelmine lehekülg")}</button> <button type="button" disabled={locked||!state.hasMore||page>=10000} onClick={()=>{setSelected('');setPage(value=>value+1);}}>{t("Järgmine lehekülg")}</button></p>
      {creating&&<OfferForm initialDay={createContext?.day} initialStaffId={createContext?.staffId} key={JSON.stringify(createContext)} refresh={revision} tenantId={tenantId} state={state} locked={locked} submit={submit} close={()=>setCreating(false)}/>}
      {booking&&<BookingEditor key={booking.id+':'+booking.version} tenantId={tenantId} state={state} booking={{...booking,noticeStatus:state.bookings.find(b=>b.id===booking.id&&b.version===booking.version)?.noticeStatus??booking.noticeStatus}} locked={locked} submit={submit}/>}
      <PolicyForm key={state.policy.version} tenantId={tenantId} policy={state.policy} locked={locked} reload={()=>setRevision(value=>value+1)}/>
    </>}
  </section>;
}
function BookingEditor({tenantId,state,booking,locked,submit}:EditorProps&{booking:BookingDetail}){
  const {t,locale}=useI18n();
  const titleRef=useRef<HTMLHeadingElement>(null);
  useEffect(()=>{titleRef.current?.focus();},[]);
  const money=(value:number)=>new Intl.NumberFormat(localeTags[locale],{style:'currency',currency:'EUR'}).format(value/100);
  const moment=(value:string,zone:string)=>new Intl.DateTimeFormat(localeTags[locale],{dateStyle:'medium',timeStyle:'short',timeZone:zone}).format(new Date(value));

  const [mode,setMode]=useState<'view'|'cancel'|'reschedule'|'status'|'revoke'>('view'),[reason,setReason]=useState(''),[override,setOverride]=useState(false),[status,setStatus]=useState('completed'),[events,setEvents]=useState<BookingHistoryItem[]|null>(null),[historyError,setHistoryError]=useState('');
  useEffect(()=>{const controller=new AbortController();read({view:'history',tenantId,bookingId:booking.id},controller.signal).then(body=>{if(!controller.signal.aborted)setEvents(body.events);}).catch(error=>{if(!controller.signal.aborted)setHistoryError(error instanceof Error?error.message:t("Ajalugu ei saanud laadida."));});return()=>controller.abort();},[tenantId,booking.id,booking.version]);
  const base={tenantId,bookingId:booking.id,version:booking.version},canChange=booking.status==='confirmed'&&(booking.canChange||state.canOverride);
  return <article><h3 ref={titleRef} tabIndex={-1}>{booking.reference} · {t(statusNames[booking.status])}</h3>
    <dl><dt>{t("Klient")}</dt><dd>{booking.name}</dd><dt>{t("Kontakt")}</dt><dd>{booking.email?<a href={'mailto:'+booking.email}>{booking.email}</a>:t("E-post puudub")}{booking.phone&&<> · <a href={'tel:'+booking.phone.replace(/[^+\d]/g,'')}>{booking.phone}</a></>}</dd><dt>{t("Teenus ja töötaja")}</dt><dd>{booking.serviceName} · {booking.staffName}</dd><dt>{t("Aeg")}</dt><dd>{moment(booking.start,state.timezone)} – {moment(booking.end,state.timezone)}</dd><dt>{t("Kokkulepitud hind ja kestus")}</dt><dd>{money(booking.price)} · {booking.duration}{t(" min")}</dd><dt>{t("Päritolu")}</dt><dd>{booking.source==='manual'?t("Käsitsi lisatud"):t("Veebist broneeritud")}</dd></dl>
    {booking.attentionReason&&<p role="status">{t("Vajab lahendamist: ")}{booking.attentionReason}{t(". Vana aeg on alles. Lepi kliendiga uus aeg kokku või tühista broneering.")}</p>}
    <p>{booking.deadline?t("Muutmise ja tühistamise tähtaeg: ")+moment(booking.deadline,state.timezone)+'.':t("Varasemad muutmistingimused puuduvad.")} {!booking.canChange&&booking.status==='confirmed'?t("Tähtajajärgne muudatus nõuab volitatud haldaja erandit ja põhjendust."):''}</p><p>{t(booking.notice)}</p><p>{t("Teavituse seisund: ")}{({pending:t("Saatmise ootel"),sending:t("Edastamisel"),sent:t("SMTP-le edastatud"),failed:t("Saatmine ebaõnnestus"),skipped:t("Jäeti saatmata"),superseded:t("Asendatud uuema muudatusega")} as Record<string,string>)[booking.noticeStatus??'']||t("Selle versiooni teavitust pole")}</p><p>{t("Uue halduslingi väljastamine muudab varasema lingi kehtetuks.")}</p>
    {mode==='view'&&<p><button type="button" disabled={locked||!canChange} onClick={()=>setMode('reschedule')}>{t("Muuda broneeringut")}</button> <button type="button" disabled={locked||!canChange} onClick={()=>setMode('cancel')}>{t("Tühista broneering")}</button> <button type="button" disabled={locked||booking.status==='cancelled'} onClick={()=>setMode('status')}>{t("Muuda seisundit")}</button> <button type="button" disabled={locked||state.policy.linkHours===null||Date.parse(booking.end)+(state.policy.linkHours??0)*3600000<=Date.now()} onClick={()=>submit({...base,action:'issue-link'})}>{t("Loo uus halduslink")}</button> <button type="button" disabled={locked} onClick={()=>setMode('revoke')}>{t("Tühista halduslink")}</button></p>}
    {mode==='reschedule'&&<OfferForm tenantId={tenantId} state={state} booking={booking} locked={locked} submit={submit} close={()=>setMode('view')}/>}
    {['cancel','status','revoke'].includes(mode)&&<form onSubmit={event=>{event.preventDefault();void submit({...base,action:mode==='revoke'?'revoke-link':mode,reason,...(mode==='cancel'?{overrideDeadline:override}:mode==='status'?{status}:{})});}}><h4>{mode==='cancel'?t("Kinnita broneeringu tühistamine"):mode==='revoke'?t("Kinnita halduslingi tühistamine"):t("Paranda broneeringu seisund")}</h4>
      {mode==='status'&&<label>{t("Uus seisund ")}<select value={status} disabled={locked} onChange={event=>setStatus(event.target.value)}><option value="completed">{t("Teenindatud")}</option><option value="no_show">{t("Ei ilmunud")}</option><option value="confirmed">{t("Kinnitatud")}</option></select></label>}
      <label>{t("Põhjus ")}{mode==='cancel'&&booking.canChange?t("(soovi korral)"):''}<textarea value={reason} maxLength={500} minLength={mode==='cancel'&&booking.canChange?0:3} required={mode!=='cancel'||!booking.canChange} disabled={locked} onChange={event=>setReason(event.target.value)}/></label>
      {mode==='cancel'&&!booking.canChange&&state.canOverride&&<label><input type="checkbox" checked={override} required disabled={locked} onChange={event=>setOverride(event.target.checked)}/> {t("Luban põhjendatud erandi pärast tähtaega")}</label>}
      <p>{mode==='cancel'?t("Broneeritud aeg vabastatakse pärast serveri kinnitust."):mode==='revoke'?t("Olemasolev link kaotab kehtivuse; broneering jääb alles."):t("Teenindatuks või mitteilmunuks saab märkida pärast broneeritud aja lõppu.")}</p><button disabled={locked}>{t("Kinnita toiming")}</button> <button type="button" disabled={locked} onClick={()=>setMode('view')}>{t("Loobu")}</button></form>}
    <details><summary>{t("Muudatuste ajalugu")}</summary>{historyError&&<p role="alert">{t(historyError)}</p>}{events===null&&!historyError&&<p>{t("Laadime ajalugu…")}</p>}<ol>{events?.map((event,index)=><li key={event.at+':'+index}>{moment(event.at,state.timezone)} · {event.actorName||t("Klient / süsteem")} · {t(eventNames[event.action])||t("Broneeringu sündmus")}{event.reason?' · '+event.reason:''}<details><summary>{t("Broneering enne ja pärast")}</summary>{event.before&&<p>{t("Enne: ")}{historySummary(event.before,state.timezone,locale)}</p>}<p>{t("Pärast: ")}{historySummary(event.after,state.timezone,locale)}</p></details></li>)}</ol>{events?.length===100&&<p>{t("Näidatakse 100 viimast muudatust.")}</p>}</details>
  </article>;
}
function OfferForm({tenantId,state,booking,locked,submit,close,refresh=0,initialDay,initialStaffId}:EditorProps&{booking?:BookingDetail;refresh?:number;initialDay?:string;initialStaffId?:string;close:()=>void}){
  const {t,locale}=useI18n();
  const titleRef=useRef<HTMLHeadingElement>(null);
  useEffect(()=>{titleRef.current?.focus();},[]);
  const money=(value:number)=>new Intl.NumberFormat(localeTags[locale],{style:'currency',currency:'EUR'}).format(value/100);
  const moment=(value:string,zone:string)=>new Intl.DateTimeFormat(localeTags[locale],{dateStyle:'medium',timeStyle:'short',timeZone:zone}).format(new Date(value));

  const [serviceId,setServiceId]=useState(booking?.serviceId??state.services.find(s=>!initialStaffId||state.assignments.some(a=>a.staffId===initialStaffId&&a.serviceId===s.id))?.id??''),[staffId,setStaffId]=useState(booking?.staffId??initialStaffId??''),[day,setDay]=useState(initialDay??state.today),[offers,setOffers]=useState<Offer[]>([]),[offer,setOffer]=useState<Offer|null>(null),[rulesVersion,setRulesVersion]=useState(state.rulesVersion),[loading,setLoading]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(0),[name,setName]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[reason,setReason]=useState(''),[override,setOverride]=useState(false);
  const [customerLanguage,setCustomerLanguage]=useState<Locale>(locale); const [sendEmail,setSendEmail]=useState(true);
  const workers=state.staff.filter(worker=>state.assignments.some(a=>a.staffId===worker.id&&a.serviceId===serviceId));
  useEffect(()=>{if(!workers.some(worker=>worker.id===staffId))setStaffId(workers[0]?.id??'');},[serviceId,state.staff,state.assignments,staffId]);
  useEffect(()=>{setOffer(null);setOffers([]);setError('');if(!serviceId||!staffId)return;const controller=new AbortController();setLoading(true);read({view:'offers',tenantId,serviceId,staffId,day,...(booking?{bookingId:booking.id}:{})},controller.signal).then((body:BookingAvailability)=>{if(!controller.signal.aborted){setOffers(body.offers);setRulesVersion(body.rulesVersion);}}).catch(error=>{if(!controller.signal.aborted)setError(error instanceof Error?error.message:t("Aegu ei saanud laadida."));}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[tenantId,serviceId,staffId,day,booking?.id,retry,state.rulesVersion,refresh]);
  return <form onSubmit={event=>{event.preventDefault();if(!offer)return;void submit({tenantId,action:booking?'reschedule':'manual-create',serviceId:offer.serviceId,staffId:offer.staffId,start:offer.start,expectedPrice:offer.price,expectedDuration:offer.duration,expectedRulesVersion:rulesVersion,...(booking?{bookingId:booking.id,version:booking.version,reason,overrideDeadline:override}:{language:customerLanguage,name,email:email.trim()||null,phone,sendEmail})});}}><h3 ref={titleRef} tabIndex={-1}>{booking?t("Vali uus pakkumine"):t("Lisa broneering käsitsi")}</h3>{!booking&&<label><input type="checkbox" checked={sendEmail} disabled={locked} onChange={e=>setSendEmail(e.target.checked)}/>{t("Saada kliendile e-kiri")}</label>}{!booking&&<label>{t("Kliendi keel")} <select value={customerLanguage} disabled={locked} onChange={e=>setCustomerLanguage(e.target.value as Locale)}>{locales.map(l=><option key={l} value={l}>{localeNames[l]}</option>)}</select></label>}
    <label>{t("Teenus ")}<select value={serviceId} required disabled={locked} onChange={event=>{setOffer(null);setServiceId(event.target.value);}}><option value="">{t("Vali teenus")}</option>{state.services.map(service=><option key={service.id} value={service.id}>{service.name}{service.online?'':t(" (ainult halduses)")}</option>)}</select></label>
    <label>{t("Töötaja ")}<select value={staffId} required disabled={locked} onChange={event=>{setOffer(null);setStaffId(event.target.value);}}><option value="">{t("Vali töötaja")}</option>{workers.map(worker=><option key={worker.id} value={worker.id}>{worker.name}</option>)}</select></label>
    <label>{t("Kuupäev ")}<input type="date" value={day} min={state.today} max={state.maxDate} required disabled={locked} onChange={event=>{setOffer(null);setDay(event.target.value);}}/></label>
    {loading&&<p role="status">{t("Laadime vabu aegu…")}</p>}{error&&<p role="alert">{t(error)} <button type="button" disabled={locked} onClick={()=>setRetry(value=>value+1)}>{t("Proovi uuesti")}</button></p>}{!loading&&!error&&serviceId&&staffId&&!offers.length&&<p>{t("Sel päeval vabu aegu pole.")}</p>}
    <ul aria-label={t("Haldaja vabad ajad")}>{!loading&&offers.map(item=><li key={item.start}><button type="button" aria-pressed={item===offer} disabled={locked} onClick={()=>setOffer(item)}>{moment(item.start,state.timezone)} · {item.duration} {t("min · ")}{money(item.price)}</button></li>)}</ul>
    {!booking&&<><label>{t("Kliendi nimi ")}<input value={name} required minLength={2} maxLength={120} disabled={locked} onChange={event=>setName(event.target.value)}/></label><label>{t("E-post (soovi korral) ")}<input type="email" value={email} maxLength={254} disabled={locked} onChange={event=>setEmail(event.target.value)}/></label><label>{t("Telefon (soovi korral) ")}<input type="tel" value={phone} maxLength={30} disabled={locked} onChange={event=>setPhone(event.target.value)}/></label>{!email.trim()&&<p>{t("E-postita broneeringule kinnituskirja ei saadeta. Anna aeg ja tingimused kliendile ise edasi.")}</p>}</>}
    {booking&&<label>{t("Muudatuse põhjus ")}{booking.canChange?t("(soovi korral)"):''}<textarea value={reason} maxLength={500} required={!booking.canChange} minLength={booking.canChange?0:3} disabled={locked} onChange={event=>setReason(event.target.value)}/></label>}
    {booking&&!booking.canChange&&state.canOverride&&<label><input type="checkbox" checked={override} required disabled={locked} onChange={event=>setOverride(event.target.checked)}/> {t("Luban põhjendatud erandi pärast tähtaega")}</label>}
    {offer&&<aside><h4>{t("Kinnita pakkumine")}</h4><p>{state.services.find(service=>service.id===offer.serviceId)?.name} · {offer.staffName} · {moment(offer.start,state.timezone)} – {moment(offer.end,state.timezone)} · {offer.duration} {t("min · ")}{money(offer.price)}</p><p>{t("Muutmine ja tühistamine: vähemalt ")}{booking?booking.cancellationHours??'teadmata':state.cancellationHours} {t("tundi enne algust. ")}{booking?t("Vana aeg jääb alles kuni uue aja kinnitamiseni."):''}</p></aside>}
    <button disabled={locked||loading||!offer}>{booking?t("Kinnita uus aeg ja hind"):t("Kinnita käsitsi broneering")}</button> <button type="button" disabled={locked} onClick={close}>{t("Loobu")}</button>
  </form>;
}
function PolicyForm({tenantId,policy,locked,reload}:{tenantId:string;policy:BookingPolicy;locked:boolean;reload:()=>void}){
  const {t,locale}=useI18n();
  const money=(value:number)=>new Intl.NumberFormat(localeTags[locale],{style:'currency',currency:'EUR'}).format(value/100);
  const moment=(value:string,zone:string)=>new Intl.DateTimeFormat(localeTags[locale],{dateStyle:'medium',timeStyle:'short',timeZone:zone}).format(new Date(value));

  const [enabled,setEnabled]=useState(policy.linkHours!==null),[hours,setHours]=useState(policy.linkHours===null?'':String(policy.linkHours)),[email,setEmail]=useState(policy.contactEmail),[phone,setPhone]=useState(policy.contactPhone),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
  async function save(event:FormEvent){event.preventDefault();if(saving||locked)return;setSaving(true);setMessage('');try{const response=await fetch('/api/admin/booking-policy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tenantId,version:policy.version,contactEmail:email.trim(),contactPhone:phone.trim(),linkHours:enabled?Number(hours):null})});const body=await response.json();if(!response.ok)throw new Error(body.error||t("Seadete salvestamine ebaõnnestus."));reload();}catch(error){setMessage(error instanceof Error?error.message:t("Seadete salvestamine ebaõnnestus."));}finally{setSaving(false);}}
  return <details><summary>{t("Ettevõtte kontakt ja halduslinkide poliitika")}</summary><p>{t("Poliitika määrab ettevõtte omanik. Kehtivus arvestatakse broneeritud aja lõpust. Olemasolevad lingid säilitavad neile määratud kehtivusreegli; uue lingi loomine tühistab sama broneeringu eelmise lingi.")}</p><form onSubmit={save}><fieldset disabled={locked||saving||!policy.canEdit}><label>{t("Avalik e-post ")}<input type="email" value={email} maxLength={254} onChange={event=>setEmail(event.target.value)}/></label><label>{t("Avalik telefon ")}<input type="tel" value={phone} maxLength={30} onChange={event=>setPhone(event.target.value)}/></label><label><input type="checkbox" checked={enabled} onChange={event=>setEnabled(event.target.checked)}/> {t("Luba uute kliendi halduslinkide väljastamine")}</label>{enabled&&<label>{t("Kehtivus tundides pärast broneeringu lõppu ")}<input type="number" min={0} max={8760} step={1} required value={hours} onChange={event=>setHours(event.target.value)}/></label>}{policy.canEdit&&<button>{t("Salvesta ettevõtte poliitika")}</button>}</fieldset></form>{message&&<p role="alert">{t(message)} <button type="button" disabled={saving||locked} onClick={reload}>{t("Laadi seaded uuesti")}</button></p>}</details>;
}
