"use client";
import {localeTags} from '@/lib/locales';
import {localizedFetch as fetch} from '@/lib/client-fetch';
import {useI18n} from '@/components/i18n-provider';

import {useEffect,useRef,useState,type FormEvent} from 'react';
type Customer={contact_redacted_at?:string|null;id:string;name:string;email:string|null;phone:string|null;version:number;merged_into_id?:string|null};
type State={customers:Customer[];hasMore:boolean;history:Array<{reference:string;serviceName:string;staffName:string;start:string;status:string;price:number}>;historyHasMore:boolean;events:Array<{at:string;actor:string;metadata:{reason?:string;before?:Customer;after?:Customer}}> ;merges:Array<{at:string;actor:string;metadata:{reason?:string;source?:Customer;target?:Customer;bookingsMoved?:number}}>;timezone:string;canEdit:boolean;canExport:boolean;canPrivacy:boolean};
const statuses:Record<string,string>={confirmed:'Kinnitatud',cancelled:'Tühistatud',completed:'Teenindatud',no_show:'Ei ilmunud'};
export default function CustomerManagement({tenantId}:{tenantId:string}){
  const {t,locale}=useI18n();

  const [search,setSearch]=useState(''),[query,setQuery]=useState(''),[page,setPage]=useState(0),[selected,setSelected]=useState(''),[state,setState]=useState<State|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0),[loading,setLoading]=useState(false);
  useEffect(()=>{const controller=new AbortController();setLoading(true);setState(null);setError('');fetch('/api/admin/customers?'+new URLSearchParams({tenantId,search:selected?'':query,page:String(page),...(selected?{customerId:selected}:{})}),{cache:'no-store',signal:controller.signal}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||t("Kliendid ei ole kättesaadavad."));if(!controller.signal.aborted)setState(b);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[tenantId,query,page,selected,revision]);
  const format=(date:string)=>new Date(date).toLocaleString(localeTags[locale],{timeZone:state?.timezone});
  return <section aria-labelledby="customers-title"><h2 id="customers-title">{t("Kliendid")}</h2>
    <form onSubmit={e=>{e.preventDefault();setQuery(search);setSelected('');setPage(0);}}><label>{t("Otsi nime, e-posti või telefoni järgi ")}<input value={search} maxLength={120} onChange={e=>setSearch(e.target.value)}/></label> <button>{t("Otsi kliente")}</button></form>
    <p>{t("Kliendid koondatakse ainult täielikult kattuvate algsete nime- ja kontaktandmete järgi. Kontaktita broneeringud jäävad eraldi. Parandus muudab kliendikaarti; varasemate broneeringute kontaktid ja teavitused säilivad.")}</p>
    {loading&&<p role="status">{t("Laadime kliente…")}</p>}{error&&<p role="alert">{t(error)} <button onClick={()=>setRevision(v=>v+1)}>{t("Proovi uuesti")}</button></p>}
    {state&&!selected&&<><ul>{state.customers.map(c=><li key={c.id}><button onClick={()=>{setSelected(c.id);setPage(0);}}>{c.name} · {c.email||t("E-post puudub")} · {c.phone||t("Telefon puudub")}</button></li>)}</ul>{!state.customers.length&&<p>{t("Kliente ei leitud.")}</p>}{state.canExport&&<p><a href={'/api/admin/customers?'+new URLSearchParams({tenantId,search:query,format:'csv'})}>{t("Ekspordi otsingu kliendid CSV-failina")}</a></p>}</>}
    {state&&selected&&<><button onClick={()=>{setSelected('');setPage(0);}}>{t("Tagasi kliendinimekirja")}</button>{state.customers[0]&&<CustomerForm key={state.customers[0].id+':'+state.customers[0].version} tenantId={tenantId} customer={state.customers[0]} canEdit={state.canEdit&&!state.customers[0].contact_redacted_at} reload={()=>setRevision(v=>v+1)}/>}<h3>{t("Broneeringute ajalugu")}</h3><ul>{state.history.map(b=><li key={b.reference}>{format(b.start)} · {b.serviceName} · {b.staffName} · {t(statuses[b.status])} · {(b.price/100).toFixed(2)} € · {b.reference}</li>)}</ul>{!state.history.length&&<p>{t("Broneeringuid pole.")}</p>}<details><summary>{t("Kliendikaardi 50 viimast parandust")}</summary><ol>{state.events.map((e,i)=><li key={i}>{format(e.at)} · {e.actor||t("Endine kasutaja")} · {e.metadata.reason}<p>{t("Enne: ")}{e.metadata.before?.name} · {e.metadata.before?.email} · {e.metadata.before?.phone}</p><p>{t("Pärast: ")}{e.metadata.after?.name} · {e.metadata.after?.email} · {e.metadata.after?.phone}</p></li>)}</ol></details></>}
    {state&&<p>{t("Lehekülg ")}{page+1}. <button disabled={page===0} onClick={()=>setPage(v=>v-1)}>{t("Eelmine")}</button> <button disabled={page>=10000||!(selected?state.historyHasMore:state.hasMore)} onClick={()=>setPage(v=>v+1)}>{t("Järgmine")}</button></p>}
    {state&&selected&&state.customers[0]&&<>{state.canPrivacy&&<CustomerPrivacy key={selected} tenantId={tenantId} customerId={selected} onRemoved={()=>setRevision(v=>v+1)}/>}
      {state.customers[0].merged_into_id?<p>{t('See kliendikaart on ühendatud teise kaardiga.')} <button onClick={()=>{setSelected(state.customers[0].merged_into_id!);setPage(0);}}>{t('Ava säilinud kliendikaart')}</button></p>:state.canEdit&&!state.customers[0].contact_redacted_at&&<CustomerMerge key={state.customers[0].id+':'+state.customers[0].version} tenantId={tenantId} source={state.customers[0]} onMerged={id=>{setSelected(id);setPage(0);setRevision(v=>v+1);}}/>}
      {!!state.merges?.length&&<details><summary>{t('Kliendikaartide ühendamised')}</summary><ol>{state.merges.map((merge,i)=><li key={i}>{format(merge.at)} · {merge.actor||t('Endine kasutaja')}<p>{merge.metadata.source?.name} ({merge.metadata.source?.email}) → {merge.metadata.target?.name} ({merge.metadata.target?.email})</p><p>{t('Üle viidud broneeringuid:')} {merge.metadata.bookingsMoved} · {merge.metadata.reason}</p></li>)}</ol></details>}
    </>}
  </section>;
}
function CustomerPrivacy({tenantId,customerId,onRemoved}:{tenantId:string;customerId:string;onRemoved:()=>void}){
 const {t}=useI18n();
 const [confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function download(e:FormEvent){e.preventDefault();if(!confirmed||busy)return;setBusy(true);setError('');try{
  const response=await fetch('/api/admin/customers/privacy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tenantId,customerId,identityConfirmed:confirmed})});
  if(!response.ok){const body=await response.json();throw Error(body.error);}
  const url=URL.createObjectURL(await response.blob());const anchor=document.createElement('a');anchor.href=url;anchor.download='customer-data.json';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
 }catch(e){setError(e instanceof Error?e.message:t('Toiming ebaõnnestus.'));}finally{setBusy(false);}}
 return <details><summary>{t('Kliendi andmetaotlus')}</summary><p>{t('Fail sisaldab valitud kliendikaardi, ühendatud kaartide ja broneeringute andmeid. Kontrolli faili enne väljastamist. Auditi, impordi ja väliste teenusepakkujate andmed vajavad eraldi läbivaatust.')}</p><form onSubmit={download}><fieldset disabled={busy}><label><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{t('Kontrollisin taotleja isikusamasust ja valitud kliendikaarti.')}</label>{' '}<button disabled={!confirmed}>{t('Laadi kliendi andmepakett')}</button></fieldset></form>{error&&<p role="alert">{t(error)}</p>}<ContactRemoval tenantId={tenantId} customerId={customerId} onRemoved={onRemoved}/></details>;
}
type RemovalPreview={customerId:string;profiles:Array<{id:string;name:string;email:string|null;phone:string|null}>;bookings:number;futureBookings:number;legalHold:boolean;importSources:number;exports:number;alreadyRemoved:boolean;fingerprint:string;canRemove:boolean};
function ContactRemoval({tenantId,customerId,onRemoved}:{tenantId:string;customerId:string;onRemoved:()=>void}){
 const {t}=useI18n(),[preview,setPreview]=useState<RemovalPreview|null>(null),[confirmed,setConfirmed]=useState(false),[identity,setIdentity]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const running=useRef(false);
 async function inspect(){if(running.current)return;running.current=true;setBusy(true);setError('');setPreview(null);setConfirmed(false);setIdentity(false);try{const response=await fetch('/api/admin/customers/privacy?'+new URLSearchParams({tenantId,customerId}),{cache:'no-store'});const body=await response.json();if(!response.ok)throw Error(body.error);setPreview(body);}catch(e){setError(e instanceof Error?e.message:t('Toiming ebaõnnestus.'));}finally{running.current=false;setBusy(false);}}
 async function remove(e:FormEvent){e.preventDefault();if(!preview?.canRemove||!confirmed||!identity||running.current)return;running.current=true;setBusy(true);setError('');try{const response=await fetch('/api/admin/customers/privacy',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({tenantId,customerId,fingerprint:preview.fingerprint,identityConfirmed:identity,confirmed})});const body=await response.json();if(!response.ok)throw Error(body.error);setPreview(null);setConfirmed(false);setIdentity(false);setMessage(body.filesPending?'Kontaktid on eemaldatud. Ekspordifailide füüsiline koristus jätkub taustal.':'Kliendi kontaktid on eemaldatud.');onRemoved();}catch(e){setError(e instanceof Error?e.message:t('Toiming ebaõnnestus.'));}finally{running.current=false;setBusy(false);}}
 return <div><h4>{t('Kliendikontaktide eemaldamine')}</h4><p>{t('Eemaldatakse nimi, e-post ja telefon valitud ning ühendatud kaartidelt, broneeringutest ja nende paranduste ajaloost. Broneeringute ajad ja teenused säilivad; see ei ole täielik anonüümimine. Arveid ei muudeta.')}</p><p>{t('Ettevõtte olemasolevad ekspordid suletakse ja halduslingid tühistatakse. Varem alla laaditud failid, saadetud kirjad ja varukoopiad vajavad eraldi käsitlemist.')}</p><button type="button" disabled={busy} onClick={()=>void inspect()}>{t('Kontrolli eemaldamise ulatust')}</button>{error&&<p role="alert">{t(error)}</p>}{message&&<p role="status">{t(message)}</p>}
 {preview&&<><ul>{preview.profiles.map(p=><li key={p.id}>{p.name} · {p.email} · {p.phone}</li>)}</ul><p>{t('Broneeringuid: {count}',{count:preview.bookings})} {t('Suletavaid eksporte: {count}',{count:preview.exports})}</p>{preview.alreadyRemoved&&<p>{t('Kliendi kontaktid on eemaldatud.')}</p>}{preview.legalHold&&<p>{t('Andmetele kehtib säilitamiskohustus.')}</p>}{preview.futureBookings>0&&<p>{t('Kliendil on tulevasi aktiivseid broneeringuid.')}</p>}{preview.importSources>0&&<p>{t('Eemalda esmalt kliendi- ja broneeringuimportide algandmed.')}</p>}{preview.canRemove&&<form onSubmit={remove}><fieldset disabled={busy}><p><label><input type="checkbox" required checked={identity} onChange={e=>setIdentity(e.target.checked)}/>{t('Kontrollisin taotleja isikusamasust ja valitud kliendikaarti.')}</label></p><p><label><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{t('Kinnitan eelvaates näidatud kontaktide pöördumatu eemaldamise.')}</label></p><button disabled={!confirmed||!identity}>{t('Eemalda kliendi kontaktid')}</button></fieldset></form>}</>}
 </div>;
}
function CustomerForm({tenantId,customer,canEdit,reload}:{tenantId:string;customer:Customer;canEdit:boolean;reload:()=>void}){
  const {t,locale}=useI18n();

  const [name,setName]=useState(customer.name),[email,setEmail]=useState(customer.email||''),[phone,setPhone]=useState(customer.phone||''),[reason,setReason]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
  async function save(e:FormEvent){e.preventDefault();if(saving)return;setSaving(true);setError('');try{const r=await fetch('/api/admin/customers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tenantId,customerId:customer.id,version:customer.version,name,email,phone,reason})});const b=await r.json();if(!r.ok)throw new Error(b.error||t("Salvestamine ebaõnnestus."));reload();}catch(e){setError(e instanceof Error?e.message:t("Serveri kinnitus puudub. Laadi kliendikaart uuesti."));}finally{setSaving(false);}}
  return <form onSubmit={save}><h3>{customer.name}</h3><fieldset disabled={!canEdit||saving||!!customer.merged_into_id}><label>{t("Nimi ")}<input value={name} required minLength={2} maxLength={120} onChange={e=>setName(e.target.value)}/></label> <label>{t("E-post ")}<input type="email" value={email} maxLength={254} onChange={e=>setEmail(e.target.value)}/></label> <label>{t("Telefon ")}<input type="tel" value={phone} maxLength={30} onChange={e=>setPhone(e.target.value)}/></label> <label>{t("Paranduse põhjus ")}<input value={reason} required minLength={3} maxLength={500} onChange={e=>setReason(e.target.value)}/></label>{canEdit&&<button>{t("Salvesta kliendikaardi parandus")}</button>}</fieldset>{error&&<p role="alert">{t(error)} <button type="button" disabled={saving} onClick={reload}>{t("Laadi kehtiv kliendikaart")}</button></p>}</form>;
}
function CustomerMerge({tenantId,source,onMerged}:{tenantId:string;source:Customer;onMerged:(id:string)=>void}){
 const {t}=useI18n(),[search,setSearch]=useState(''),[candidates,setCandidates]=useState<Customer[]>([]),[target,setTarget]=useState<Customer|null>(null),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const running=useRef(false),pending=useRef<{signature:string;key:string}|null>(null);
 async function find(e:FormEvent){e.preventDefault();if(running.current)return;running.current=true;setBusy(true);setError('');setTarget(null);setConfirmed(false);try{const r=await fetch('/api/admin/customers?'+new URLSearchParams({tenantId,search}),{cache:'no-store'});const b=await r.json();if(!r.ok)throw Error(b.error);setCandidates(b.customers.filter((c:Customer)=>c.id!==source.id));}catch(e){setError(e instanceof Error?e.message:t('Toiming ebaõnnestus.'));}finally{running.current=false;setBusy(false);}}
 async function merge(e:FormEvent){e.preventDefault();if(!target||!confirmed||running.current)return;running.current=true;setBusy(true);setError('');const data={tenantId,sourceId:source.id,targetId:target.id,sourceVersion:source.version,targetVersion:target.version,reason,confirmed:true};const signature=JSON.stringify(data);if(pending.current?.signature!==signature)pending.current={signature,key:crypto.randomUUID()};try{const r=await fetch('/api/admin/customers',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,requestKey:pending.current.key})});const b=await r.json();if(!r.ok)throw Error(b.error);onMerged(b.id);}catch(e){setError(e instanceof Error?e.message:t('Toiming ebaõnnestus.'));}finally{running.current=false;setBusy(false);}}
 return <details><summary>{t('Ühenda duplikaat teise kliendikaardiga')}</summary><p>{t('Vali sama inimese säiliv kliendikaart. Selle kaardi andmed jäävad kehtima; broneeringute algsed kontaktid säilivad. Ühine e-posti aadress ei tõenda, et tegemist on sama inimesega.')}</p>
  {error&&<p role="alert">{error}</p>}
  <form onSubmit={find}><label>{t('Otsi säilivat kliendikaarti')} <input value={search} maxLength={120} onChange={e=>setSearch(e.target.value)} disabled={busy}/></label>{' '}<button disabled={busy}>{t('Otsi sobivaid kliendikaarte')}</button></form>
  <p>{t('Otsing näitab kuni 50 vastet; vajadusel täpsusta otsingut.')}</p>
  <form onSubmit={merge}><fieldset disabled={busy}><legend>{t('Ühendamise ülevaade')}</legend><label>{t('Säiliv kliendikaart')} <select required value={target?.id??''} onChange={e=>{setTarget(candidates.find(c=>c.id===e.target.value)??null);setConfirmed(false);}}><option value="">{t('Vali klient')}</option>{candidates.map(c=><option key={c.id} value={c.id}>{c.name} · {c.email} · {c.phone} · {c.id.slice(0,8)}</option>)}</select></label>
   <p>{t('Ühendatav kaart:')} {source.name} · {source.email} · {source.phone}</p>{target&&<p>{t('Säiliv kaart:')} {target.name} · {target.email} · {target.phone}</p>}
   <p><label>{t('Ühendamise põhjus')} <input required minLength={10} maxLength={500} value={reason} onChange={e=>{setReason(e.target.value);setConfirmed(false);}}/></label></p>
   <p><label><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{t('Kontrollisin, et mõlemad kaardid kuuluvad samale inimesele.')}</label></p>
   <button disabled={!target||!confirmed}>{t('Ühenda kliendikaardid')}</button>
  </fieldset></form>
 </details>;
}
