"use client";
import {useState,type FormEvent} from 'react';
import type {ManagedGroup,ManagedService,ManagedStaff,ManagedAssignment,ServiceManagementState} from '@/lib/service-management-contracts';
type Save=(action:string,payload:Record<string,unknown>)=>Promise<boolean>;
type Props={tenantId:string;catalog:ServiceManagementState;busy:boolean;save:Save};
const text=(d:FormData,key:string)=>String(d.get(key)||'').trim();
const num=(d:FormData,key:string)=>Number(text(d,key));
const money=(d:FormData,key:string)=>Math.round(num(d,key)*100);
const optional=(d:FormData,key:string,cents=false)=>text(d,key)===''?null:(cents?money(d,key):num(d,key));
function Input({name,label,value='',max=150}:{name:string;label:string;value?:string;max?:number}){return <label>{label} <input name={name} defaultValue={value} maxLength={max} required/></label>;}
function NumberInput({name,label,value,price=false,inherit=false}:{name:string;label:string;value:number|null;price?:boolean;inherit?:boolean}){
  return <label>{label} <input name={name} type="number" min={name.toLowerCase().includes('duration')?5:0} max={price?1000000:name.toLowerCase().includes('duration')?720:240} step={price?'0.01':'1'} defaultValue={value===null?'':price?(value/100).toFixed(2):value} required={!inherit} placeholder={inherit?'Teenuse vaikeväärtus':undefined}/></label>;
}
function Flags({active=true,online=true,withOnline=true}:{active?:boolean;online?:boolean;withOnline?:boolean}){return <><label><input name="active" type="checkbox" defaultChecked={active}/> Aktiivne (märge maha = arhiveeritud)</label>{withOnline&&<label><input name="online" type="checkbox" defaultChecked={online}/> Veebis broneeritav</label>}</>;}
function GroupForm({item,groups,save}:{item?:ManagedGroup;groups:ManagedGroup[];save:Save}){
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,d=new FormData(form);if(await save('save-group',{id:item?.id,version:item?.version,name:text(d,'name'),parentId:text(d,'parentId')||null,active:d.has('active')})&&!item)form.reset();}
  return <form onSubmit={submit}><Input name="name" label="Grupi nimi" value={item?.name} max={100}/><label>Ülemgrupp <select name="parentId" defaultValue={item?.parentId||""}><option value="">Põhikategooria</option>{groups.filter(g=>{let current:ManagedGroup|undefined=g;for(let i=0;current&&i<=groups.length;i++){if(current.id===item?.id)return false;current=groups.find(p=>p.id===current?.parentId);}return true;}).map(g=><option key={g.id} value={g.id}>{g.path}</option>)}</select></label><Flags active={item?.active} withOnline={false}/><button>Salvesta grupp</button></form>;
}
function ServiceForm({item,groups,save}:{item?:ManagedService;groups:ManagedGroup[];save:Save}){
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,d=new FormData(form);if(await save('save-service',{id:item?.id,version:item?.version,groupId:text(d,'groupId'),name:text(d,'name'),description:text(d,'description'),defaultPrice:money(d,'defaultPrice'),defaultDuration:num(d,'defaultDuration'),bufferBefore:num(d,'bufferBefore'),bufferAfter:num(d,'bufferAfter'),active:d.has('active'),online:d.has('online')})&&!item)form.reset();}
  return <form onSubmit={submit}><label>Teenusegrupp <select name="groupId" defaultValue={item?.groupId||''} required><option value="">Vali grupp</option>{groups.map(g=><option key={g.id} value={g.id}>{g.path}{!g.active?' (arhiveeritud)':''}</option>)}</select></label><Input name="name" label="Teenuse nimi" value={item?.name}/><label>Lühikirjeldus <textarea name="description" defaultValue={item?.description} maxLength={1000}/></label><NumberInput name="defaultPrice" label="Vaikehind (€)" value={item?.defaultPrice??0} price/><NumberInput name="defaultDuration" label="Vaikekestus (min)" value={item?.defaultDuration??30}/><NumberInput name="bufferBefore" label="Ettevalmistus (min)" value={item?.bufferBefore??0}/><NumberInput name="bufferAfter" label="Lõpetamine (min)" value={item?.bufferAfter??0}/><Flags active={item?.active} online={item?.online}/><button>Salvesta teenus</button></form>;
}
function StaffForm({item,save}:{item?:ManagedStaff;save:Save}){
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,d=new FormData(form);if(await save('save-staff',{id:item?.id,version:item?.version,name:text(d,'name'),title:text(d,'title'),bio:text(d,'bio'),photoUrl:text(d,'photoUrl'),active:d.has('active'),online:d.has('online')})&&!item)form.reset();}
  return <form onSubmit={submit}><Input name="name" label="Töötaja nimi" value={item?.name} max={120}/><label>Amet <input name="title" defaultValue={item?.title} maxLength={150}/></label><label>Avalik lühitutvustus <textarea name="bio" defaultValue={item?.bio} maxLength={1000}/></label><label>Foto HTTPS-aadress (valikuline) <input name="photoUrl" type="url" pattern="https://.*" defaultValue={item?.photoUrl} maxLength={2000}/></label><Flags active={item?.active} online={item?.online}/><button>Salvesta töötaja</button></form>;
}
function PricingForm({service,item,save}:{service:ManagedService;item?:ManagedAssignment;save:Save}){
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);await save('save-pricing',{serviceId:service.id,staffId:item?.staffId,version:item?.version??service.version,price:item?optional(d,'price',true):money(d,'price'),duration:item?optional(d,'duration'):num(d,'duration')});}
  return <form onSubmit={submit}><NumberInput name="price" label="Hind (€)" value={item?item.price:service.defaultPrice} price inherit={!!item}/><NumberInput name="duration" label="Kestus (min)" value={item?item.duration:service.defaultDuration} inherit={!!item}/><button>Salvesta hind ja kestus</button></form>;
}
function AssignmentForm({catalog,item,save}:{catalog:ServiceManagementState;item?:ManagedAssignment;save:Save}){
  const [serviceId,setServiceId]=useState(item?.serviceId||'');
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,d=new FormData(form);if(await save('save-assignment',{serviceId:item?.serviceId||serviceId,staffId:item?.staffId||text(d,'staffId'),version:item?.version??0,price:optional(d,'price',true),duration:optional(d,'duration'),bufferBefore:optional(d,'bufferBefore'),bufferAfter:optional(d,'bufferAfter'),active:d.has('active')})&&!item){form.reset();setServiceId('');}}
  return <form onSubmit={submit}>{!item&&<><label>Teenus <select required value={serviceId} onChange={e=>setServiceId(e.target.value)}><option value="">Vali teenus</option>{catalog.services.filter(s=>s.active).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Töötaja <select name="staffId" required key={serviceId} defaultValue=""><option value="">Vali töötaja</option>{catalog.staff.filter(st=>st.active&&!catalog.assignments.some(a=>a.serviceId===serviceId&&a.staffId===st.id)).map(st=><option key={st.id} value={st.id}>{st.name}</option>)}</select></label></>}<NumberInput name="price" label="Erihind (€)" value={item?.price??null} price inherit/><NumberInput name="duration" label="Erikestus (min)" value={item?.duration??null} inherit/><NumberInput name="bufferBefore" label="Ettevalmistuse erand (min)" value={item?.bufferBefore??null} inherit/><NumberInput name="bufferAfter" label="Lõpetamise erand (min)" value={item?.bufferAfter??null} inherit/><Flags active={item?.active} withOnline={false}/><button>Salvesta seos</button></form>;
}
export default function ServiceManagement({tenantId,catalog,busy,save}:Props){
  const run:Save=(action,payload)=>save(action,{...payload,tenantId});
  return <section aria-labelledby="services-admin-title"><h3 id="services-admin-title">Teenused ja töötajad</h3><p>Hinnad on eurodes. Arhiveerimine ja hinnakirja muutmine ei muuda varasemaid broneeringuid. Grupi arhiveerimine peidab ka selle alamgrupid ja teenused. Veebis peidetud teenuste käsitsi broneerimine lisandub kalendri peatükis.</p><fieldset disabled={busy}><legend>Hinnakiri</legend>
  {catalog.canEditStructure&&<><h4>Teenusegrupid</h4><p>Loo põhikategooriad ja vajaduse korral nende alamgrupid. Broneeritav teenus kuulub valitud gruppi.</p>{catalog.groups.map(g=><details key={g.id}><summary>{g.path}{!g.active?' · arhiveeritud':''}</summary><GroupForm key={g.version} item={g} groups={catalog.groups} save={run}/></details>)}<details><summary>Lisa teenusegrupp</summary><GroupForm groups={catalog.groups} save={run}/></details></>}
  <h4>Teenused</h4>{catalog.services.length===0&&<p>Teenuseid veel pole.</p>}{catalog.services.map(s=><details key={s.id}><summary>{s.name} · {(s.defaultPrice/100).toFixed(2)} € · {s.defaultDuration} min{!s.active?' · arhiveeritud':!s.online?' · veebis peidetud':''}</summary>{catalog.canEditStructure?<ServiceForm key={s.version} item={s} groups={catalog.groups} save={run}/>:<PricingForm key={s.version} service={s} save={run}/>}</details>)}
  {catalog.canEditStructure&&<details><summary>Lisa teenus</summary>{catalog.groups.length?<ServiceForm groups={catalog.groups} save={run}/>:<p>Lisa esmalt teenusegrupp.</p>}</details>}
  {catalog.canEditStructure&&<><h4>Töötajad</h4><p>Profiil ei vaja sisselogimiskontot. Siia lisa ainult avalik tutvustus. Graafikuid saad hallata töögraafikute jaotises.</p>{catalog.staff.map(st=><details key={st.id}><summary>{st.name}{!st.active?' · arhiveeritud':!st.online?' · veebis peidetud':''}</summary><StaffForm key={st.version} item={st} save={run}/></details>)}<details><summary>Lisa töötaja</summary><StaffForm save={run}/></details></>}
  <h4>Töötaja teenused</h4><p>Tühi erandiväli pärib teenuse vaikeväärtuse, ka pärast vaikeväärtuse muutmist. Täidetud väli jääb eraldi määratud väärtuseks.</p>
  {catalog.assignments.map(a=>{const s=catalog.services.find(s=>s.id===a.serviceId)!,st=catalog.staff.find(st=>st.id===a.staffId)!;return <details key={a.serviceId+':'+a.staffId}><summary>{s.name} — {st.name}{!a.active?' · arhiveeritud':''}</summary><ul>{([['price','Hind',s.defaultPrice,'€'],['duration','Kestus',s.defaultDuration,'min'],['bufferBefore','Ettevalmistus',s.bufferBefore,'min'],['bufferAfter','Lõpetamine',s.bufferAfter,'min']] as const).map(([key,label,base,unit])=><li key={key}>{label}: {key==='price'?((a[key]??base)/100).toFixed(2):(a[key]??base)} {unit} — {a[key]===null?'päritud':a[key]===base?'eraldi määratud, sama kui vaikeväärtus':'erisus teenuse vaikeväärtusest'}</li>)}</ul>{catalog.canEditStructure?<AssignmentForm key={a.version} catalog={catalog} item={a} save={run}/>:<PricingForm key={a.version} service={s} item={a} save={run}/>}</details>;})}
  {catalog.canEditStructure&&<details><summary>Seo töötaja teenusega</summary><AssignmentForm catalog={catalog} save={run}/></details>}
  </fieldset></section>;
}
